<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiBaruDalam ProsesMenunggu P_427f57</name>
   <tag></tag>
   <elementGuidId>2c924242-4fb0-4da6-b88f-8daeffbd4132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[1]/div/div[2]/div[2]/div[1]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b1-Dropdown4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1291984c-a044-4858-adef-361ce4414166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>6afb9d48-7ea9-45f4-8f8a-3a1d649f846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8143c4aa-6fbc-4e88-96bf-87986dad176e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b1-Dropdown4</value>
      <webElementGuid>77444de0-7e9f-402e-ada5-c101befa32af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiBaruDalam ProsesMenunggu PersetujuanDisetujuiDikembalikanTidak Selesai</value>
      <webElementGuid>c574f1a1-d1f6-499e-8ebb-75c356056244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b1-Dropdown4&quot;)</value>
      <webElementGuid>e229c9cd-420e-411e-a172-ac9b3e55f442</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b3-b1-Dropdown4']</value>
      <webElementGuid>6258c811-cf42-4f0a-a301-869d04ed1e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b1-Dropdown4-container']/select</value>
      <webElementGuid>87381f0a-4e43-4a4c-a785-becef94cb434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/following::select[1]</value>
      <webElementGuid>ebfd4f83-4316-431d-aa80-2fb53bc014bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>a011d568-0762-4d7d-98ec-eb0575cd1c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::select[1]</value>
      <webElementGuid>447fef3a-ab7e-4ccb-b849-05c9fbe01da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task  ID'])[1]/preceding::select[1]</value>
      <webElementGuid>318bdc42-0355-4e5f-813b-1fe9952318e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>3a88011c-2377-443b-ae68-7242e0c7e729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b3-b1-Dropdown4' and (text() = 'Pilih OpsiBaruDalam ProsesMenunggu PersetujuanDisetujuiDikembalikanTidak Selesai' or . = 'Pilih OpsiBaruDalam ProsesMenunggu PersetujuanDisetujuiDikembalikanTidak Selesai')]</value>
      <webElementGuid>4441e598-f5b2-4897-9f2d-9750b761f9aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
