<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiSEMARANGSURABAYAJAKARTA GR_05f5b9</name>
   <tag></tag>
   <elementGuidId>5e439522-dd07-47f3-a726-17223e9dc1e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[1]/div/div[1]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b1-Dropdown1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d00961c8-afe0-4f7f-9bad-5a989737c930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>2b6c4afd-dbf6-4aa2-a5bf-d092fa02f65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>939258b6-6581-435f-bb80-ab717ce60df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b1-Dropdown1</value>
      <webElementGuid>6dd48235-374c-4e85-88f2-4195a8554738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH</value>
      <webElementGuid>41ecf2a5-89e1-4c2e-b227-8ec73e12204a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b1-Dropdown1&quot;)</value>
      <webElementGuid>2ced1787-fc24-494b-8dac-404b63a8357f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b3-b1-Dropdown1']</value>
      <webElementGuid>309bc832-348a-4dda-8944-e66aec60732f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b1-Dropdown1-container']/select</value>
      <webElementGuid>87739086-c3fd-4ec9-a78d-02188b0aa14a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::select[1]</value>
      <webElementGuid>9e93de58-580b-45ca-960f-6b795134f953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/following::select[1]</value>
      <webElementGuid>cc40e4c9-a938-4412-93a9-71e187041c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>7cf44130-6440-4f0c-a7e3-7854b8a39c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/preceding::select[1]</value>
      <webElementGuid>2ddcc7c3-1206-4796-a42a-7d22b6fd2659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4ff8ed8f-43d1-4c9e-bd58-22beec21446f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b3-b1-Dropdown1' and (text() = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH' or . = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH')]</value>
      <webElementGuid>fd8b09c7-fb18-49b1-9c40-6e3440bc230f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
