<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 0.00_b3-b3-b8-b3-Selected</name>
   <tag></tag>
   <elementGuidId>43786f54-0060-41df-bb13-48af0bba75b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div/section/section/div/div[2]/article/div/div/div[1]/div[2]/div/div/div[1]/span[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-b3-Selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4af98c65-9ec2-4401-805a-e31ec431db77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>351197ec-ef5d-4279-96cf-94351eee547d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4b3998f8-d2e5-489c-ac2b-db8f2c9964e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-b3-Selected</value>
      <webElementGuid>1b49ac18-8e18-4648-9546-bc518923ff54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-b3-Selected&quot;)</value>
      <webElementGuid>3aaf1b46-7f69-47d7-849e-4271f5d25a03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b8-b3-Selected']</value>
      <webElementGuid>d6e45c09-ded5-4ab2-a869-f98a6608700f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b8-b3-PettyCashSummary']/div/span/input</value>
      <webElementGuid>2366def3-e2c4-4b74-8b31-207ba7e5645e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div[2]/div/div/div/span/input</value>
      <webElementGuid>6415f826-d49c-4d2e-8be8-f0b05d7abeed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b3-b8-b3-Selected']</value>
      <webElementGuid>3ea92349-dd46-469e-8a3a-8252511f824c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
