<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Karyawan_b3-b3-b9-b2-NamaKaryawan</name>
   <tag></tag>
   <elementGuidId>232437a7-2ee6-426c-bdae-807dd06e0896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[1]/div/div[2]/div[1]/div[1]/div/div/div[1]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b9-b2-NamaKaryawan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7bc88357-6998-4c1a-8cfb-69acefcc8c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>de8b4e14-71b6-4f2e-bf40-08cbc83d4cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>882b56d5-ed91-4b1d-951d-0040258924d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50ec5130-7611-4e37-83ff-9d55f91db107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e988e0d1-f26a-4a34-bf41-f0bc898fb3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b9-b2-NamaKaryawan</value>
      <webElementGuid>1e289754-ae9a-4605-8c2d-33392d5b6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b9-b2-NamaKaryawan&quot;)</value>
      <webElementGuid>3dd15628-8972-423e-9896-d338af5dc1cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b9-b2-NamaKaryawan']</value>
      <webElementGuid>7f708730-25f3-4f31-94e0-128ac76a4f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b9-b2-b1-Column1']/div/span/input</value>
      <webElementGuid>10bf2c6a-04a9-4b24-bcb7-7fe3dfb80971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>34e6b61d-bb26-40d2-9cef-2a1ffbc27250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'b3-b3-b9-b2-NamaKaryawan']</value>
      <webElementGuid>7d805359-f71b-4ef4-a322-6ace9aa4f667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
