<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tindak Lanjut_b3-b3-b6-l2_0-775_0-IsS_240854</name>
   <tag></tag>
   <elementGuidId>a6bc66fc-c13b-4521-9645-45c45264b63b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div/section/section/div/div[1]/article/div/div/div[2]/div[2]/div/table/tbody/tr/td[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b6-l2_0-775_0-IsSelected2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52bd4cb5-fcc0-47a8-88a8-3a91e344bde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ac976052-b742-43a4-b1b7-80b7897d90f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>61712018-3208-4606-a504-56a9337ffb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b6-l2_0-775_0-IsSelected2</value>
      <webElementGuid>a547e891-c63d-4260-b1b9-7965752322cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b6-l2_0-775_0-IsSelected2&quot;)</value>
      <webElementGuid>bb024ec9-9300-40bf-b5dd-20380fa6ae0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b6-l2_0-775_0-IsSelected2']</value>
      <webElementGuid>0c7497d3-12c2-4d54-93af-850dfc5f9890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b6-DokumenPersetujuan']/div[2]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>84719e9a-2142-4c60-8638-d1804cb66eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>054674a8-c41b-4618-8bc6-7d5182389aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b3-b6-l2_0-775_0-IsSelected2']</value>
      <webElementGuid>b8094a16-05be-49f5-9eae-d7a3f1ae89ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
