<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah_b3-b3-b9-l1_0-903_0-IsPICUtama</name>
   <tag></tag>
   <elementGuidId>6a715214-9e57-4d0a-adfa-3868f2c9e62d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[1]/div/div[2]/div[2]/div[2]/table/tbody/tr/td[8]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b9-l1_0-903_0-IsPICUtama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f67d4a8b-0106-4bb5-8193-1b74c25a90f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4d9c66ff-2ab0-45ee-bc06-1da9e6f6f7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2c339816-d5f6-42d5-8d75-1efb315bd983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b9-l1_0-903_0-IsPICUtama</value>
      <webElementGuid>e1f1fad5-0844-4dac-8327-c79595807170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b9-l1_0-903_0-IsPICUtama&quot;)</value>
      <webElementGuid>2a0e45b4-1131-4ad3-a3ad-30af95c5d6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b9-l1_0-903_0-IsPICUtama']</value>
      <webElementGuid>357e02fe-1494-4965-be08-a2d61d633974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b9-Table']/div[2]/table/tbody/tr/td[8]/span/input</value>
      <webElementGuid>226e1884-a029-4b04-a780-e1d9c071f7ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/span/input</value>
      <webElementGuid>9b85318d-ab0b-4cd8-9d8b-b905c6999683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b3-b9-l1_0-903_0-IsPICUtama']</value>
      <webElementGuid>ef05cfed-57be-4358-87e4-10ff90e48222</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
