<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OUTSTANDING PETTY CASH</name>
   <tag></tag>
   <elementGuidId>84eea528-a1a3-4202-9bf5-fd5e0ccfceec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div[3]/div/section/header/div[1]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-Title > div.bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>162b1331-2a02-4c5f-a49d-581c4304ff4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>d176bceb-a1cb-4ca3-a323-25d984e25aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OUTSTANDING PETTY CASH</value>
      <webElementGuid>0835ea31-6f12-450f-96fe-96d21f6eb9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-Title&quot;)/div[@class=&quot;bold&quot;]</value>
      <webElementGuid>e1931c2d-4ca9-4150-b462-2e2435dcf666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-Title']/div</value>
      <webElementGuid>961dffcf-95e7-4fd1-b7f3-f096271c2709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETTY CASH REIMBURSED'])[1]/following::div[3]</value>
      <webElementGuid>3e05408f-5e41-4cd5-ac42-1c60c1e49497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::div[9]</value>
      <webElementGuid>6853f7e9-5ca2-41c2-a64d-24c1f84f0a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Allocation'])[1]/preceding::div[2]</value>
      <webElementGuid>a28a7abb-a7c2-45f6-845a-7c6464e2ca93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Petty Cash'])[1]/preceding::div[2]</value>
      <webElementGuid>43124ca9-930f-4d96-bf4c-cd588855e061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OUTSTANDING PETTY CASH']/parent::*</value>
      <webElementGuid>a187805c-9685-4194-b0a1-befdc0ee4b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/div</value>
      <webElementGuid>b9e58033-88d2-41a6-8fae-afda286a89e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OUTSTANDING PETTY CASH' or . = 'OUTSTANDING PETTY CASH')]</value>
      <webElementGuid>c4528ffe-638d-4e6b-831a-0c9bd3959700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
