<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BARU_b3-b1-b6-l4_0-213_0-TenggatWaktu_680c36</name>
   <tag></tag>
   <elementGuidId>65898531-178f-43e5-af1c-aaa44d130046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div[3]/div/section/section/div/div[1]/article/div/div/div[2]/div[2]/div/table/tbody/tr/td[9]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b6-l4_0-213_0-TenggatWaktuPenyelesaian2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a03e52c-6d3f-4a4e-ba10-03f2a97531e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>4ad3155a-5c33-494f-81ec-2d1a43a1bf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>cf685f50-96ca-45ee-8e4d-b78d33b259aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b59c881f-a108-47b1-b28e-6619d889f7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b6-l4_0-213_0-TenggatWaktuPenyelesaian2</value>
      <webElementGuid>03069630-9ca3-4d77-9f42-e4e9ac5c28d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b6-l4_0-213_0-TenggatWaktuPenyelesaian2&quot;)</value>
      <webElementGuid>89a6b168-b2fb-4490-814c-b2a5461b7d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b6-l4_0-213_0-TenggatWaktuPenyelesaian2']</value>
      <webElementGuid>18cc49bf-8f72-4573-93f5-83bbaf3f3ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b6-DokumenPersetujuan']/div[2]/div/table/tbody/tr/td[9]/span/input</value>
      <webElementGuid>a2535c67-2a5c-4af1-8dbc-8bd1318fd2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/span/input</value>
      <webElementGuid>5cb91256-f260-46e8-a5d2-60c1dab001b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b6-l4_0-213_0-TenggatWaktuPenyelesaian2']</value>
      <webElementGuid>ed5a40ce-424b-4577-8dde-8d4b82220695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
