<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_BARU_b3-b1-b6-l4_0-213_0-TextArea__32085d</name>
   <tag></tag>
   <elementGuidId>64c34e86-812a-4770-8f5c-e693cb563d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div[3]/div/section/section/div/div[1]/article/div/div/div[2]/div[2]/div/table/tbody/tr/td[10]/div/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b6-l4_0-213_0-TextArea_TindakLanjut2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5493ce5b-2b34-4486-ae71-19dbe8c17ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>eccfcc18-0414-47f7-86fe-489322e21c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>70179f47-d958-4d54-8cdf-bb86360a4e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>30af1d08-aba7-4e44-ac17-fea7898ccf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b6-l4_0-213_0-TextArea_TindakLanjut2</value>
      <webElementGuid>65439b53-76de-4803-82f8-c65c076f7f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b6-l4_0-213_0-TextArea_TindakLanjut2&quot;)</value>
      <webElementGuid>28f01fdd-f035-408f-ad86-2a02dde6cd5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b1-b6-l4_0-213_0-TextArea_TindakLanjut2']</value>
      <webElementGuid>c5c90e62-ad5c-4809-af00-478062b29e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b6-DokumenPersetujuan']/div[2]/div/table/tbody/tr/td[10]/div/span/textarea</value>
      <webElementGuid>84aab1e3-38a3-4ded-9ac6-e125c16bb789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dfc1b854-22c8-4333-a38b-0a07edbee809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b1-b6-l4_0-213_0-TextArea_TindakLanjut2']</value>
      <webElementGuid>6f4a630d-b8a3-4e1c-a83e-c966913f97d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
