<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Operasional Cabang</name>
   <tag></tag>
   <elementGuidId>7451a454-efd1-490e-bf5c-53c81c9457df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-16_5-b4-l1-29_5-b1-SubMenuHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f66e17c-f065-4850-82b3-ba52d6935267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>da5f2df1-77af-4bd4-b734-27c5a6c71cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-16_5-b4-l1-29_5-b1-SubMenuHeader</value>
      <webElementGuid>1236372e-122a-4af3-9f24-89ec6dbfad5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e01ba147-8191-4887-8e1d-8e8c32b44b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95effb91-e8c2-45ff-a51b-160e58502777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-16_5-b4-l1-29_5-b1-Items</value>
      <webElementGuid>13fa470d-5452-4636-9798-fc64a5c675c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>40d61dd3-592e-4d0a-8f1b-52e6718f9c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e8724d73-5387-4d23-af22-155b41180c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operasional Cabang</value>
      <webElementGuid>c246aedb-bb4a-4b36-8467-e6fcc5935945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-16_5-b4-l1-29_5-b1-SubMenuHeader&quot;)</value>
      <webElementGuid>416b8885-819e-4ea8-9668-5fbfc6cbd749</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-16_5-b4-l1-29_5-b1-SubMenuHeader']</value>
      <webElementGuid>b66bc699-7ff0-47e8-b278-556559c7fce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-16_5-b4-l1-29_5-b1-Submenu']/div</value>
      <webElementGuid>dd4361fa-b56b-4275-bc5d-a8b7c32cf701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showroom/Supplier'])[1]/following::div[4]</value>
      <webElementGuid>9a6883a0-168e-41bc-aa7b-ba05f619c2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[1]/following::div[4]</value>
      <webElementGuid>db3447ba-917d-48c2-a225-f831d782356a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Petty Cash'])[1]/preceding::div[3]</value>
      <webElementGuid>90c4cd0f-9521-4f5e-8b75-1f713eb5525c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>6b613d44-dd87-4135-ba6f-82e236274acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-16_5-b4-l1-29_5-b1-SubMenuHeader' and (text() = 'Operasional Cabang' or . = 'Operasional Cabang')]</value>
      <webElementGuid>8646633c-e46e-4050-bc1b-404668518fa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
