<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah_b3-b2-b9-l1_0-390_0-IsPICUtama</name>
   <tag></tag>
   <elementGuidId>2091e437-e598-434b-9609-10c946736974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[1]/div/div[2]/div[2]/div[2]/table/tbody/tr/td[8]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b9-l1_0-390_0-IsPICUtama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5dc7de46-5b4e-44e7-9eee-f5e7aad3c56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f5d716b-7b9d-4d9d-9fda-ff19d4147ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>05a1c1ad-3ff7-4f68-a784-9873f67a3973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b9-l1_0-390_0-IsPICUtama</value>
      <webElementGuid>ed9b7ad3-d89d-48b3-8b42-d2c618ba231c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b9-l1_0-390_0-IsPICUtama&quot;)</value>
      <webElementGuid>68a6f932-ba8f-4ed4-b84a-f93e257c86e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b2-b9-l1_0-390_0-IsPICUtama']</value>
      <webElementGuid>b987cb83-3540-44a9-b59e-83a8f6eec7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b9-Table']/div[2]/table/tbody/tr/td[8]/span/input</value>
      <webElementGuid>72277fdf-9ece-4766-81d6-bd80429563bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/span/input</value>
      <webElementGuid>1b14233a-590f-4964-bab5-414fd6917ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b2-b9-l1_0-390_0-IsPICUtama']</value>
      <webElementGuid>14dc6317-a0c9-4b47-ab96-2ac3574392bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
