<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Karyawan_b3-b2-b9-b2-NamaKaryawan</name>
   <tag></tag>
   <elementGuidId>fd7f119b-d049-4224-bf46-798e1e25010e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[1]/div/div[2]/div[1]/div[1]/div/div/div[1]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b9-b2-NamaKaryawan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9133270b-630c-4ba7-a03e-8ea28cbdb28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>39acba7b-118f-4e71-8e5e-d5ad93d7c259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>43f783b9-3a95-4da6-b30a-bc760cc8a211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c70a8e33-094a-400c-8e7c-50fc0b575802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c6f6c3da-c72f-461f-bf8e-18e01f1e7663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b9-b2-NamaKaryawan</value>
      <webElementGuid>e848eaf0-09f3-4cd5-8c97-266304ce1a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b9-b2-NamaKaryawan&quot;)</value>
      <webElementGuid>25b0b741-1589-4212-a344-73678d09ccfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b2-b9-b2-NamaKaryawan']</value>
      <webElementGuid>58ed2c19-e7ab-40ec-a73b-db5f4f365795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b9-b2-b1-Column1']/div/span/input</value>
      <webElementGuid>72cda2a0-4637-4a71-9bd8-ca5f24b6a1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>5dde8948-f4e2-47a2-9c46-c5d22ab12928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'b3-b2-b9-b2-NamaKaryawan']</value>
      <webElementGuid>98887628-6901-45f6-9a3b-49305b7860b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
