<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tindak Lanjut_b3-b2-b6-l2_0-795_0-IsS_0e7e70</name>
   <tag></tag>
   <elementGuidId>b97a902f-a6d6-4f67-8c68-af20531c16a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div/section/section/div/div[1]/article/div/div/div[2]/div[2]/div/table/tbody/tr[1]/td[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b6-l2_0-795_0-IsSelected2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0968594-9122-43e7-897d-226f3a8a6f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e7d680a2-0ed9-4402-81eb-76b3d191e29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c2d15697-a17e-43bf-a009-1eac734eee78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b6-l2_0-795_0-IsSelected2</value>
      <webElementGuid>fec223c9-e534-4e63-b760-9e41f5e013c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b6-l2_0-795_0-IsSelected2&quot;)</value>
      <webElementGuid>df73c3ca-f833-4461-8e37-3caddd028748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b2-b6-l2_0-795_0-IsSelected2']</value>
      <webElementGuid>0dce1506-5e8b-43b7-8720-4a465c0ca5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b6-DokumenPersetujuan']/div[2]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>745e489b-ad8b-48ec-abc0-40b46a98c2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>1dd6a269-67f8-4f8f-9315-13ab3df56a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b2-b6-l2_0-795_0-IsSelected2']</value>
      <webElementGuid>93f0f25d-482c-4153-9966-4d1e54643c3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
