<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan_b3-b1-b8-b10-TextArea_Catatan</name>
   <tag></tag>
   <elementGuidId>ddbfc433-db44-421c-9ffc-76d92b095616</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[2]/div/div/div[2]/div/section/section/div/div[2]/article/div/div/div[3]/div/div[1]/div[3]/div[2]/div[1]/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b8-b10-TextArea_Catatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>260837e7-e804-4731-9df6-cf6f208d3c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>5fc889de-be4a-41c6-9eb2-db7680cc5c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>78f283e4-4f71-4118-9b75-f93460e13e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>11ba3117-7426-4ffa-8d6c-c35d13190128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b8-b10-TextArea_Catatan</value>
      <webElementGuid>ac8b28c0-3a31-453e-b2f3-e0e4d365236c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6276abe6-3fdd-4084-ae04-6eab739e3f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b8-b10-TextArea_Catatan&quot;)</value>
      <webElementGuid>adc710d5-5906-41a0-a344-54720b1f37e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b1-b8-b10-TextArea_Catatan']</value>
      <webElementGuid>901ded2e-fcf6-480d-8911-34f2b4ab69e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b8-$b10']/div/div[3]/div[2]/div/span/textarea</value>
      <webElementGuid>8bec2957-24df-42a6-ad73-8e6811fe0825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/textarea</value>
      <webElementGuid>7de64757-2e24-4655-96ba-b50b931364e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b1-b8-b10-TextArea_Catatan']</value>
      <webElementGuid>af813791-f18b-4ba6-a913-a92da62093c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
