<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a categorySelesaiSedang Berja_127797</name>
   <tag></tag>
   <elementGuidId>27fd5d02-108e-416b-aa17-dfed334b30c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div/div/div/div/div[3]/div[2]/form/div/div/div[1]/div/div/div/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-l1-770_0-b2-TindakLanjutStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>88f72f88-afee-42c3-8414-314e196a1789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>bb70cbdd-5207-44f7-b640-fab8da243bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>27224c24-e9f3-4483-a0e2-e957fb95e43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l1-770_0-b2-TindakLanjutStatus</value>
      <webElementGuid>c1f5e681-c9e2-4cd5-b516-c002d2c4e2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a categorySelesaiSedang BerjalanBatal</value>
      <webElementGuid>50a8f19d-5367-4613-b32c-22ca2ed0f366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l1-770_0-b2-TindakLanjutStatus&quot;)</value>
      <webElementGuid>1c566c67-20b6-4c2d-930b-9aa370a676e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-l1-770_0-b2-TindakLanjutStatus']</value>
      <webElementGuid>ba2e4b3a-4c73-4069-af51-9a1fac447813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l1-770_0-b2-TindakLanjutStatus-container']/select</value>
      <webElementGuid>e0e4201d-b719-43ec-9d44-2b5f84bc83db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[13]/following::select[1]</value>
      <webElementGuid>3c8d758d-7c3d-4bab-9cdd-4a3867657c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindak Lanjut'])[2]/following::select[1]</value>
      <webElementGuid>866428a9-46db-48f5-a450-ee257965a233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[2]/preceding::select[1]</value>
      <webElementGuid>28152ee8-1cbc-4e29-a4d0-8878e7646ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[14]/preceding::select[1]</value>
      <webElementGuid>3806cf23-5445-41fb-bc1d-8fdcacaea12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div[2]/div/select</value>
      <webElementGuid>a49f444a-a6ff-49e3-b0db-05d2893f8c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-l1-770_0-b2-TindakLanjutStatus' and (text() = 'Select a categorySelesaiSedang BerjalanBatal' or . = 'Select a categorySelesaiSedang BerjalanBatal')]</value>
      <webElementGuid>ebba0c6b-f288-4eb2-a574-70428e7080c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
