<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__b3-l1-770_0-b2-TextArea_TindakLan_1d9cf7</name>
   <tag></tag>
   <elementGuidId>875d9497-9c37-475e-9a6d-c834870101f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div/div/div/div/div[3]/div[2]/form/div/div/div[2]/div/div/div[2]/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-l1-770_0-b2-TextArea_TindakLanjutCatatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6ca66045-9376-4cfa-93fa-255108f2f0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>7a2407c9-09ed-4acb-bd92-0a95d55a9fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>b18617da-7dd9-437e-8b4a-15055b41ac24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>c523355c-f1d2-4ac6-8a2f-215b52fa9de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l1-770_0-b2-TextArea_TindakLanjutCatatan</value>
      <webElementGuid>68a8f5a9-024e-4212-bef0-5888232d29dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l1-770_0-b2-TextArea_TindakLanjutCatatan&quot;)</value>
      <webElementGuid>f2a417b8-daee-4e79-b9e2-0c345bca2bde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l1-770_0-b2-TextArea_TindakLanjutCatatan']</value>
      <webElementGuid>ebcfa70d-1789-4f21-92fe-de8d4dcf189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l1-770_0-b2-b19-Column2']/span/textarea</value>
      <webElementGuid>0327e7e3-4df5-476d-bfce-d9635cc30b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/textarea</value>
      <webElementGuid>c7bf9bc8-a35c-4d3c-82a4-8fc42ab77bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l1-770_0-b2-TextArea_TindakLanjutCatatan']</value>
      <webElementGuid>83e60706-818c-4673-b5fc-ff2905442c86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
