<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_b3-b3-b8-l3_0-198_0-b5-Input_Mask</name>
   <tag></tag>
   <elementGuidId>46740c1c-7366-4ac9-a8b6-5127d55894d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[1]/td[5]/div/div/div/div/div[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-l3_0-198_0-b5-Input_Mask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4aef32bb-310f-4cdc-a6d2-c42070b08854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-align-right OSFillParent masked-value</value>
      <webElementGuid>40fee527-1a24-4f50-9959-18e8fbd1b765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fad7f7b-5b12-4154-93f8-aca4b07b9704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c59eaa5-469b-40b6-974b-5a38da3de987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-l3_0-198_0-b5-Input_Mask</value>
      <webElementGuid>6117e5c4-2f7f-4284-91cf-50e418feb91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>8265afe8-3017-497f-9c13-2c6408edccd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0.00</value>
      <webElementGuid>88ba833a-22b6-45b4-9d40-6d14559a90f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-l3_0-198_0-b5-Input_Mask&quot;)</value>
      <webElementGuid>b7f67658-0a5a-40da-bb9d-cb1222d2f300</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b8-l3_0-198_0-b5-Input_Mask']</value>
      <webElementGuid>a9b47922-9fe2-4ac3-9865-ee5407a444c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b8-l3_0-198_0-b5-MaskedContent']/span/input</value>
      <webElementGuid>1f217195-0fe6-475a-b414-8c5f48e33040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/div/div/span/input</value>
      <webElementGuid>2b4478c2-37ea-43e1-80f7-8584715da940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b3-b8-l3_0-198_0-b5-Input_Mask' and @placeholder = 'Rp 0.00']</value>
      <webElementGuid>559ccc2b-e0f4-4ae0-8516-7a612efb0fad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
