<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 2,000.00_b3-b3-b6-l4_0-254_1-Input_506b82</name>
   <tag></tag>
   <elementGuidId>04d24449-af68-4aba-a84f-420d411149a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[2]/td[6]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b6-l4_0-254_1-Input_TanggalTransaksiKwitansi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2cdc1eef-4ddd-42b1-a8f8-02cf3a7555a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>ccd79644-1aa2-491e-a702-e99fc4c4eaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4ce6d3df-d275-4449-b32e-88a15b5146e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dad417a6-1c4f-4391-a2a1-bd549737696f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2022-02-24</value>
      <webElementGuid>eafdde04-a53d-471d-aba6-c46d8f1bef89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b6-l4_0-254_1-Input_TanggalTransaksiKwitansi</value>
      <webElementGuid>a97e01dc-c0c1-45bb-a34a-e5c49dc3ae3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b6-l4_0-254_1-Input_TanggalTransaksiKwitansi&quot;)</value>
      <webElementGuid>6656b54f-73cd-4cdf-b850-365d847f2429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b6-l4_0-254_1-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>e450a685-bc06-4119-8643-9f441512ac94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b3-b6-TableReimbursed']/tbody/tr[2]/td[6]/div/span/input</value>
      <webElementGuid>00fdba62-d9db-4f14-b34d-8367999f3f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/div/span/input</value>
      <webElementGuid>66a84bd1-e97c-433f-be49-337a1bc15335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b3-b6-l4_0-254_1-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>81e29552-9a3f-4176-9664-2d38c7b2fc63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
