<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 2,000.00_b3-b3-b6-l4_0-254_1-b4-In_b1876f</name>
   <tag></tag>
   <elementGuidId>23b482b6-59fc-4d25-a2fb-2dca232c2237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[2]/td[7]/div/div/div/div/div[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b6-l4_0-254_1-b4-Input_Mask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f23b0b7-ddb9-452f-bc91-785cc31d15f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-align-right OSFillParent masked-value</value>
      <webElementGuid>23340c97-56b9-470a-b55b-51d70cf3743c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8e719b8-0697-4211-a5fe-d4c7ef22f830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b7e4e1c-bf32-461a-8a53-adf3b5be08c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8e575c26-818e-4eb7-99da-61c447fd4600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b01c9c4f-ce59-4fb5-9f17-55be2c19ff15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b6-l4_0-254_1-b4-Input_Mask</value>
      <webElementGuid>e8ef2c3f-8c71-4230-93e7-9de15e33b83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>f21f7ccb-8d85-4374-b99d-c9bb29661880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0.00</value>
      <webElementGuid>ca30cb98-c208-4ea5-9fd9-f976ea81bf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b6-l4_0-254_1-b4-Input_Mask&quot;)</value>
      <webElementGuid>46a70ece-794a-484b-abf0-ede2a8de6fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b6-l4_0-254_1-b4-Input_Mask']</value>
      <webElementGuid>2b4d95bc-bece-4c28-a707-81c8a0e497f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b6-l4_0-254_1-b4-MaskedContent']/span/input</value>
      <webElementGuid>1e7689ae-2e33-47d9-bf50-29e70ab77c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/div/div/div/div/div/span/input</value>
      <webElementGuid>fd7603b5-9684-4c06-9fc1-1366cdb05dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b3-b6-l4_0-254_1-b4-Input_Mask' and @placeholder = 'Rp 0.00']</value>
      <webElementGuid>29806ab3-6e85-47cc-a720-ba4acab27a2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
