<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lihat Dokumen_b3-b3-b8-l3_0-198_1-Inp_595912</name>
   <tag></tag>
   <elementGuidId>c5bd2b30-9df8-4154-aa46-e27e4b492e48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[2]/td[4]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-l3_0-198_1-Input_TanggalTransaksiKwitansi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62f493bb-0ecd-4fe9-9b04-9fa7ec292775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>0218f180-e8e4-4609-b11e-7f7799bea15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>eb2f0b05-8d64-410c-8934-9f89dbc33f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62027220-f7fc-4cec-b242-c67eb301e4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1900-01-01</value>
      <webElementGuid>2ceffd1b-303f-4953-927b-b537653505c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-l3_0-198_1-Input_TanggalTransaksiKwitansi</value>
      <webElementGuid>e966f168-5c25-45d0-a117-9a8cc5393676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-l3_0-198_1-Input_TanggalTransaksiKwitansi&quot;)</value>
      <webElementGuid>93e6d43e-7e41-4560-9c99-8bf7ebb9c071</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b8-l3_0-198_1-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>508e4b9f-c2f9-40de-8061-e20b5a16b2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b3-b8-pettyCash']/tbody/tr[2]/td[4]/div/span/input</value>
      <webElementGuid>5c9b42b4-7ebc-43fa-98c5-035273651c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/span/input</value>
      <webElementGuid>ac3ca836-38c9-4603-ad0f-e118781544d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b3-b8-l3_0-198_1-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>883d8bbb-45e5-426d-9708-bdd205d7537a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
