<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_b3-b3-b8-l3_0-205_0-TanggalClaim</name>
   <tag></tag>
   <elementGuidId>24929fdf-ea67-4308-848c-71770e09e9d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[1]/td[2]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-l3_0-205_0-TanggalClaim</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68b86701-a062-4998-a703-621c7b8fceda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e8b81d84-2e54-4ed8-aef7-7dfaecba545c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>3f333ba3-5309-4eba-9944-53692ed18a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51174038-6d34-4ce7-853a-be941d9ec9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2022-02-26</value>
      <webElementGuid>446076a2-0c34-407f-9e54-8d6c66d99eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-l3_0-205_0-TanggalClaim</value>
      <webElementGuid>a5a12cbd-7758-4874-ba7c-a36bd61b1806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-l3_0-205_0-TanggalClaim&quot;)</value>
      <webElementGuid>71350304-36b7-4e04-bd91-ab8cb24d86b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b8-l3_0-205_0-TanggalClaim']</value>
      <webElementGuid>9c93c9ef-d500-4340-a11b-fff6df59a348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b3-b8-pettyCash']/tbody/tr/td[2]/span/input</value>
      <webElementGuid>85850846-5b7d-420b-a242-e9a32fa7b6d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/input</value>
      <webElementGuid>e2f6db93-3efa-489f-916b-f3228a5b2e7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b3-b8-l3_0-205_0-TanggalClaim']</value>
      <webElementGuid>1b52e14e-9674-4007-9029-e96790beccc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
