<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lihat Dokumen_b3-b3-b8-l3_0-198_1-Tan_91eb6f</name>
   <tag></tag>
   <elementGuidId>3321e28d-fad8-4bad-91c7-496d05b46e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[2]/td[2]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-l3_0-198_1-TanggalClaim</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa3ac4c7-4353-47bf-a78b-8668c8ecf6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>7e23c51a-1051-437c-a54e-a9afb1eaa7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4639faeb-1113-4458-8a3c-e62197ee8a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23fa6ad5-11f6-4189-9af3-2571e13f7be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2022-02-26</value>
      <webElementGuid>cc29d60c-a587-4ff0-aed9-8d6f1f885eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-l3_0-198_1-TanggalClaim</value>
      <webElementGuid>1a24ed34-9c9a-41f3-a25e-464e63397375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-l3_0-198_1-TanggalClaim&quot;)</value>
      <webElementGuid>380e0a7e-8f56-4311-b7a8-9c97e9a03b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b3-b8-l3_0-198_1-TanggalClaim']</value>
      <webElementGuid>6d1c0822-2d6c-4880-a520-85ae998e19a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b3-b8-pettyCash']/tbody/tr[2]/td[2]/span/input</value>
      <webElementGuid>b22ddac0-7626-4caa-a5a9-413267d86034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/span/input</value>
      <webElementGuid>91d45120-346b-465e-924c-e72c055582a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b3-b8-l3_0-198_1-TanggalClaim']</value>
      <webElementGuid>232b3758-a3dd-4253-9dc4-128fb01b8bd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
