<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiSesuaiTidak Sesuai_1</name>
   <tag></tag>
   <elementGuidId>2c71e374-57b3-48aa-954c-ccac0c58ade7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[2]/td[10]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b6-l4_0-267_3-Kesesuaian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>094c0da3-62d3-497a-8b60-7c32a7746b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>c99e71e1-c26b-44cb-8e56-4aaa5027ec41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>feb3faa8-6ab6-4b59-b36d-79fb822485e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b6-l4_0-267_3-Kesesuaian</value>
      <webElementGuid>c18c01c2-1181-4848-a7fd-282a1e1ae492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiSesuaiTidak Sesuai</value>
      <webElementGuid>9b81ccca-094f-4bf9-9e70-da7495204f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b6-l4_0-267_3-Kesesuaian&quot;)</value>
      <webElementGuid>0a3e2d01-92de-44ba-83e4-d945a51729d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b3-b6-l4_0-267_3-Kesesuaian']</value>
      <webElementGuid>eb6d51c1-4ab6-44c8-93ca-d6bd15cab6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b6-l4_0-267_3-Kesesuaian-container']/select</value>
      <webElementGuid>d018bcfe-6f39-4acd-a52c-1bdc427644ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 450,000.00'])[2]/following::select[1]</value>
      <webElementGuid>a8be8b32-e721-4fbc-ab7f-d1198f5a2300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 450,000.00'])[1]/following::select[1]</value>
      <webElementGuid>5f9fd057-10ea-4942-89b6-9b09ff9a7272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[5]/preceding::select[2]</value>
      <webElementGuid>66c33f16-18f3-422d-a375-64586a08126d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automobile Expenses 1'])[2]/preceding::select[2]</value>
      <webElementGuid>a3c429f8-8ba1-4da5-9951-211878a2cb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[10]/div/div/select</value>
      <webElementGuid>ed06bb9d-567c-4237-807c-f4158d836945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b3-b6-l4_0-267_3-Kesesuaian' and (text() = 'Pilih OpsiSesuaiTidak Sesuai' or . = 'Pilih OpsiSesuaiTidak Sesuai')]</value>
      <webElementGuid>8162d691-7760-493b-818c-35f190ada322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
