<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih kategori temuanRendahSedangTinggi</name>
   <tag></tag>
   <elementGuidId>2b4f2dde-9c3b-48ff-aa2c-dc80d5110fe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[4]/div/div/div[2]/div/div/div[1]/div/div[6]/div/div/div[2]/div/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-b8-KategoriTemuanDropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ddc00f63-de38-4b38-9766-8630fc9374fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>cbef41c4-71bf-4f5b-b972-1d07208553c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61bc4dae-3612-42f4-b580-5975f6f60d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-b8-KategoriTemuanDropdown</value>
      <webElementGuid>cc514284-3781-4ac2-833d-6dfe3b1dc6a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih kategori temuanRendahSedangTinggi</value>
      <webElementGuid>71eed9c3-5581-45a8-a251-f3903a9ebb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-b8-KategoriTemuanDropdown&quot;)</value>
      <webElementGuid>415bfdc5-cf62-4d30-a1dd-3c4c7d7322ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b3-b8-b8-KategoriTemuanDropdown']</value>
      <webElementGuid>f75f8f2b-b786-431d-a76d-3073bbfed56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b8-b8-KategoriTemuanDropdown-container']/select</value>
      <webElementGuid>91b087d6-2caa-4d46-876d-29dbbe123181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[10]/following::select[1]</value>
      <webElementGuid>352fc532-1963-4e2d-8fe9-2f5e30f74736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori Temuan'])[4]/following::select[1]</value>
      <webElementGuid>10adf605-202f-449e-b9cd-b383b82f14d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[4]/preceding::select[1]</value>
      <webElementGuid>3806e687-4a1b-4323-a0dd-163391430245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[11]/preceding::select[1]</value>
      <webElementGuid>ebd39332-2d9b-4b25-a9ce-9d6fbf4b8c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>180ebe63-e723-4c92-ae56-86c60b0ea67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b3-b8-b8-KategoriTemuanDropdown' and (text() = 'Pilih kategori temuanRendahSedangTinggi' or . = 'Pilih kategori temuanRendahSedangTinggi')]</value>
      <webElementGuid>80274e42-3a40-44ee-9ccd-9d211a2422ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
