<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__b3-b3-b8-b8-TextArea_Catatan2</name>
   <tag></tag>
   <elementGuidId>668904c7-b8c7-4e01-99e1-b50e62c3ffb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[4]/div/div/div[2]/div/div/div[1]/div/div[7]/div/div/div[2]/div/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-b8-TextArea_Catatan2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7d03f0de-5af6-4779-89d1-7dee027ea122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom</value>
      <webElementGuid>a6edea72-cf5b-498f-9dcb-95dd9f886a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9d7f5e12-cff3-46d1-9af8-50fed4022c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>398a111d-64d5-4afa-ba4d-41cbcb5c779b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-b8-TextArea_Catatan2</value>
      <webElementGuid>3d7ca3e2-cf01-4ba0-b378-2add9cc1d22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-b8-TextArea_Catatan2&quot;)</value>
      <webElementGuid>c6031471-7b3c-498a-b6a7-bc01b7802d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b3-b8-b8-TextArea_Catatan2']</value>
      <webElementGuid>d94e1e47-e6cb-4d96-b6f5-dc93aeb38bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b8-b8-b20-Column2']/div/span/textarea</value>
      <webElementGuid>f87cea73-b163-449f-a5f1-8b9e15d8445e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/textarea</value>
      <webElementGuid>5223cde7-c484-4f82-83a7-f82ace783512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b3-b8-b8-TextArea_Catatan2']</value>
      <webElementGuid>d0fe395f-c965-40de-87ba-e416782b0528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
