<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Rp. 0,00_b3-b3-b8-l3_0-198_1-TextA_0ec2b1</name>
   <tag></tag>
   <elementGuidId>631da01a-cfbb-4511-b9b7-02e529c2ca3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[2]/td[10]/div/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-l3_0-198_1-TextArea_Catatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6def6e2a-fd4b-433e-a78a-83e8df4fdf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>0a7535c0-6ca4-4c8f-b350-772a63a6629d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f2ffca3b-6797-4efa-8fbc-d292810284aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>2407c9fe-5e91-46e8-ae1b-ff7db59925f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-l3_0-198_1-TextArea_Catatan</value>
      <webElementGuid>5cf55370-117d-40be-be63-a2aae7977660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-l3_0-198_1-TextArea_Catatan&quot;)</value>
      <webElementGuid>8363a854-8532-4210-b087-1e4bd637a3cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b3-b8-l3_0-198_1-TextArea_Catatan']</value>
      <webElementGuid>e3a68a10-3e5a-4316-a3f2-60b25444f8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b3-b8-pettyCash']/tbody/tr[2]/td[10]/div/span/textarea</value>
      <webElementGuid>7fcde55a-e7c8-4d24-b8b8-6514a9f366b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[10]/div/span/textarea</value>
      <webElementGuid>402c6319-e5bc-4001-8f5d-6fd86298ec9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b3-b8-l3_0-198_1-TextArea_Catatan']</value>
      <webElementGuid>07688b8f-d7a7-41ed-8efa-c6215838fcd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
