<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Branch</name>
   <tag></tag>
   <elementGuidId>45a95776-44ce-478a-9bc4-c86614fc9c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-b1-b4-BRANCH_DROPDOWN']/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-BRANCH_DROPDOWN > label.mandatory.OSFillParent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c32b2d27-a37c-43af-bfb0-7288492fbb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mandatory OSFillParent</value>
      <webElementGuid>80b8e608-ffc8-49e1-a6a0-b3637372a9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>b3-b1-b4-Branch</value>
      <webElementGuid>5c31cdf1-8296-453a-8813-ae5e8eec78e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Branch :</value>
      <webElementGuid>33eb7aa0-f2e2-40ad-ab01-425dbd98fcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-BRANCH_DROPDOWN&quot;)/label[@class=&quot;mandatory OSFillParent&quot;]</value>
      <webElementGuid>958a91ea-be6a-4911-bfdd-01a449b94317</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-BRANCH_DROPDOWN']/label</value>
      <webElementGuid>bc845092-63c2-4b2a-8c14-0c14c66037ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Claim :'])[1]/following::label[1]</value>
      <webElementGuid>108ebbb1-8859-4237-b4b9-a7bb9714f444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Penugasan'])[1]/following::label[2]</value>
      <webElementGuid>ecedd3d7-9a89-4739-8510-8cad0e82b9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penugasan :'])[1]/preceding::label[1]</value>
      <webElementGuid>ef625f7a-b295-455a-9601-04c410edf26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::label[2]</value>
      <webElementGuid>1c9bb035-becd-479d-99ff-da0f1a5aba71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Branch :']/parent::*</value>
      <webElementGuid>16591f0e-fc81-43d3-af5a-9bce65ab8243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>c05d08b2-7f9c-4efb-9351-a45971ed2460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Branch :' or . = 'Branch :')]</value>
      <webElementGuid>5c4c7a81-733a-4b19-9845-9f978c5cd462</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
