<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiSEMARANGSURABAYAJAKARTA GR_05f5b9</name>
   <tag></tag>
   <elementGuidId>d8902134-d67a-4469-8b55-52b04081b571</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div/div[2]/form/div[2]/div/div/div[1]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b1-Dropdown1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fd51d26b-23ac-4029-ac1d-e8e2c962643e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>4b77c63b-67f6-4f16-af9d-ef5f52564c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4177a924-b647-4d1d-8595-7f60920a276a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b1-Dropdown1</value>
      <webElementGuid>85a722dc-b0ae-4d54-9a5e-1a2171416a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH</value>
      <webElementGuid>56b5d794-3e05-465e-8120-171b74eaa9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b1-Dropdown1&quot;)</value>
      <webElementGuid>fec67cfb-c7fc-456f-a1dc-964f6c52d70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b3-b1-Dropdown1']</value>
      <webElementGuid>912c24c4-f3b2-4c86-b31a-aec793c31b7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b1-Dropdown1-container']/select</value>
      <webElementGuid>81aef799-379e-4fdf-8603-ea7102b9ea90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::select[1]</value>
      <webElementGuid>600b84c5-7664-4451-95ea-f2a02364a8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/following::select[1]</value>
      <webElementGuid>1ca04a0b-82d0-46e8-b24a-bec15b9dd610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>3297dfb0-84ba-4bac-bcd1-a777564f999a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/preceding::select[1]</value>
      <webElementGuid>313982d0-787d-4571-bb5c-189bfd14c58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>46bc21d8-7c7f-4cee-a8eb-69b792e18afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b3-b1-Dropdown1' and (text() = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH' or . = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH')]</value>
      <webElementGuid>23910442-a8ec-4af6-b8c0-db685ffc8902</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
