<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiIQBAL PUTRA TAWAKALGIANDI _5675aa</name>
   <tag></tag>
   <elementGuidId>e5dbbf88-6433-4b86-ae20-b46d5c404b24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div/div[2]/form/div[3]/div/div/div[1]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b4-Penugasan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>055e25be-837a-4cc0-9ed7-afa6ef539341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>0ec92d25-ca38-4a05-997e-a6aabf275fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee9468c6-b3ed-4113-9e15-f7ecdc97c192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b4-Penugasan</value>
      <webElementGuid>32b22204-b77b-4bc0-a69f-bc0892865d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY</value>
      <webElementGuid>7e3bc719-744c-44b0-af3b-a6bd53853b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b4-Penugasan&quot;)</value>
      <webElementGuid>0af25700-3b56-4892-b746-3dab4e091949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b4-Penugasan']</value>
      <webElementGuid>34aca528-9fad-4f07-a83e-616eb9c653a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b4-Penugasan-container']/select</value>
      <webElementGuid>1dd3fa55-487a-4b7a-8830-47162862af8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penugasan :'])[1]/following::select[1]</value>
      <webElementGuid>7dd8c161-8f99-43b1-ac4d-56813cb53e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch :'])[1]/following::select[2]</value>
      <webElementGuid>8dd207e2-0ee1-46e1-992c-60841bf76794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::select[1]</value>
      <webElementGuid>b8988414-c757-452e-ba38-f1e0309c78bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[1]/preceding::select[1]</value>
      <webElementGuid>3729c91c-66e8-4c52-a073-160ca9162b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/select</value>
      <webElementGuid>def565fd-fb25-4896-bf28-9424fdbaa728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b4-Penugasan' and (text() = 'Pilih OpsiIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY' or . = 'Pilih OpsiIQBAL PUTRA TAWAKALGIANDI EGHY GILRANDY')]</value>
      <webElementGuid>aa80f878-0a89-4dd7-ae43-02dbd6e4097f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
