<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Untuk Regresi Sprint 1</description>
   <name>User-CBU-Flow</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9d7e5ee7-147d-4335-8601-42b54deb283b</testSuiteGuid>
   <testCaseLink>
      <guid>e2d8768a-315c-4aad-b6f3-a8013555ec86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/SPV-CBU-Create-Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>2616f0ac-3ac3-419d-a413-638de03489ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/SPV-CBU-Assign-Staff</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>dc1eedad-f81b-4219-a845-03c96a78ff32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/Staff-CBU-Assign-And-Draft</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a32db23-d51f-4234-87b6-896f35c4a049</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97bf2eba-381b-45ab-9dd1-513e6124eefc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4a48dae-fe50-4c20-8c3c-13ac5a8cb7b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2c714306-c791-4312-89e9-5048512925cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/Staff-CBU-Assign-And-Submit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e78e4f-914d-4e8a-afad-bd0e956c727b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21bfa8c6-598f-4159-b9a4-e1a6ab2181e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98df2427-70c5-4cb8-b390-6a47961b3fe1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/SPV-CBU-Persetujuan</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>95fd9cc4-0496-4445-bc2d-19a7a0a6978d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/SPV-CBU-Assign-PIC</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>55795857-757e-45d9-9b74-778d152158de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/PIC-Submit-Tindak-Lanjut</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0369b133-2b16-416e-8af6-0cbc7921852d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c745a05b-05e3-45af-b5b8-f04db5bafceb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b210e066-0b9f-4125-9456-817872f6cb20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint-1/SPV-PIC-CBU/SPV-Submit-Tindak-Lanjut</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
