<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__b3-b2-b1-EndDate</name>
   <tag></tag>
   <elementGuidId>900780c0-d8f5-467b-8167-b32678780a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[1]/div[2]/span[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b1-EndDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31fffbad-e9e2-483c-b08b-a09521fdd4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0ed5a153-b933-4c14-b731-67c9bbbca872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>cd1141ed-ce86-40dc-a9c5-cd842035ba59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ecde32f-1239-47dd-89eb-c6b470d14310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-03-11</value>
      <webElementGuid>d1af0a40-8896-400f-ae30-fe05ddf3b849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-EndDate</value>
      <webElementGuid>06678a10-e78e-4992-a4cf-f0bae7332868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b1-EndDate&quot;)</value>
      <webElementGuid>ceb56d2c-2ada-4e81-a3b3-3cdffb8a3831</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b2-b1-EndDate']</value>
      <webElementGuid>aed327ab-0aef-4e24-8580-eca1aa31e5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-$b1']/div/div/div[2]/span[2]/input</value>
      <webElementGuid>2ceb6c1c-c307-434d-8b18-0b6095f5d326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>9c4c93aa-92d4-4dd0-854f-f0d3d2112282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-b1-EndDate']</value>
      <webElementGuid>6f2afe62-6d87-4300-b6ad-e17cb35a63a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
