<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select BranchSAMPIT RBUBATAM RBUPONT_2152ea</name>
   <tag></tag>
   <elementGuidId>908aee10-3b31-4447-a31c-67949d0bb85b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[2]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b1-Branch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1104da02-c641-45ad-94ef-5b3ea4bc8bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>91221ce5-9664-4071-8a3f-a232d3975a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71383151-ae7d-4b27-9d4d-57af9809bdd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-Branch</value>
      <webElementGuid>3dcc466b-00e5-4b38-84a0-9d69d265e69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select BranchSAMPIT RBUBATAM RBUPONTIANAK RBUPALANGKARAYA RBUNDF JOGLOMAKASAR ABU 1MALANG RBU 1KARAWANG RBU 1BANDUNG ABU 1SURABAYA ABU 1SEMARANG RBU 1JAKARTA ABU 1JAKARTA ABU 2JAKARTA ABU 3JAKARTA ABU 4PEKANBARU ABU 1BALI ABU 1PALEMBANG ABU 1TANGERANG ABU 1NDF BANDUNGNDF DENPASARNDF KALIMALANGBANJARMASIN RBU 1JAMBI ABU 1NDF ALAM SUTRA</value>
      <webElementGuid>843fa2ef-7ece-4bea-8d20-51fea6e9b2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b1-Branch&quot;)</value>
      <webElementGuid>f8720394-7892-4f8d-8350-ca8649cf1302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b2-b1-Branch']</value>
      <webElementGuid>02076fa4-b3c1-4f33-8651-ee8d7c41fb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b1-Branch-container']/select</value>
      <webElementGuid>7f785262-e3df-400b-b373-6cc9ab5394af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/following::select[1]</value>
      <webElementGuid>5f3411ad-1233-4ba1-a19c-de52d5b05c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/following::select[1]</value>
      <webElementGuid>a89bb889-20ba-413d-9e4e-f38762589e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>aeff7e01-ab2c-4a24-a803-97fc345ba7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/preceding::select[1]</value>
      <webElementGuid>ac0db43b-89f0-453b-9e1d-83d969c2d5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>30f27057-bdd5-41ae-b5a4-98acbcdb6abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b2-b1-Branch' and (text() = 'Select BranchSAMPIT RBUBATAM RBUPONTIANAK RBUPALANGKARAYA RBUNDF JOGLOMAKASAR ABU 1MALANG RBU 1KARAWANG RBU 1BANDUNG ABU 1SURABAYA ABU 1SEMARANG RBU 1JAKARTA ABU 1JAKARTA ABU 2JAKARTA ABU 3JAKARTA ABU 4PEKANBARU ABU 1BALI ABU 1PALEMBANG ABU 1TANGERANG ABU 1NDF BANDUNGNDF DENPASARNDF KALIMALANGBANJARMASIN RBU 1JAMBI ABU 1NDF ALAM SUTRA' or . = 'Select BranchSAMPIT RBUBATAM RBUPONTIANAK RBUPALANGKARAYA RBUNDF JOGLOMAKASAR ABU 1MALANG RBU 1KARAWANG RBU 1BANDUNG ABU 1SURABAYA ABU 1SEMARANG RBU 1JAKARTA ABU 1JAKARTA ABU 2JAKARTA ABU 3JAKARTA ABU 4PEKANBARU ABU 1BALI ABU 1PALEMBANG ABU 1TANGERANG ABU 1NDF BANDUNGNDF DENPASARNDF KALIMALANGBANJARMASIN RBU 1JAMBI ABU 1NDF ALAM SUTRA')]</value>
      <webElementGuid>263e1be3-2c66-4e94-92bd-8fc54b040297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
