<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Operasional Cabang</name>
   <tag></tag>
   <elementGuidId>849dc165-6886-4d7c-9429-460486e46e54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[4]/div/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-16_10-b4-l1-55_5-b1-SubMenuHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9aa147f-b6d9-4f87-ba7c-483f5fd65e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>94c15a5d-ade1-4838-97ee-e4de405a484b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-16_10-b4-l1-55_5-b1-SubMenuHeader</value>
      <webElementGuid>1ac11df3-5332-4035-9cfd-a96b636b9fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44cf1ab2-e9a1-41a5-b2e4-227980b04d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d1fa6f5d-858a-4f66-b3a1-5fcbf6ec32f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-16_10-b4-l1-55_5-b1-Items</value>
      <webElementGuid>695e8fe9-d24b-4025-9ea0-6051e0b169f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>acd11c5a-a9d0-4d3a-96e1-a0f1d6b54943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a07967d-a589-4cb7-afe1-8b191e51346b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operasional Cabang</value>
      <webElementGuid>0a06ff00-98bd-43e8-a9ee-7718bc066bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-16_10-b4-l1-55_5-b1-SubMenuHeader&quot;)</value>
      <webElementGuid>e3619444-038d-43ca-a539-52f6f933e2a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-16_10-b4-l1-55_5-b1-SubMenuHeader']</value>
      <webElementGuid>70caca72-5412-4b5a-b1d6-01e46e4f2b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-16_10-b4-l1-55_5-b1-Submenu']/div</value>
      <webElementGuid>eed18611-16fd-45bd-a70b-b46516c207df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showroom/Supplier'])[3]/following::div[4]</value>
      <webElementGuid>249400e5-5133-455c-8582-ca688e253a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[3]/following::div[4]</value>
      <webElementGuid>f10d0ae4-960f-474e-91e4-1dbf679275d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Petty Cash'])[3]/preceding::div[3]</value>
      <webElementGuid>73e82056-203e-4b0a-819f-6442ac2109e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>9b76260c-f154-4575-a12c-9e9d5a74d5ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-16_10-b4-l1-55_5-b1-SubMenuHeader' and (text() = 'Operasional Cabang' or . = 'Operasional Cabang')]</value>
      <webElementGuid>5831a460-fd21-4115-965d-31952c44c1cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
