<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Input_PasswordVal</name>
   <tag></tag>
   <elementGuidId>583be565-ce3a-43d8-867f-80fb8a87539a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Input_PasswordVal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Input_PasswordVal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9ac63a4-429e-4d12-80fa-84405f30d1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control login-password OSFillParent</value>
      <webElementGuid>c16356eb-dfb7-4ff5-9885-31da4bdfbf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e4f364ff-20bb-4923-8edc-046fbb5615c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dbd3f959-e6d4-4d48-9166-055c50378925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Input_PasswordVal</value>
      <webElementGuid>5307fe1d-847c-410e-b72d-053cd2c8f5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Input_PasswordVal&quot;)</value>
      <webElementGuid>99de9047-9c6b-448a-9cb6-b27a0b0ab9f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Input_PasswordVal']</value>
      <webElementGuid>09efbae1-3e49-47de-8bc6-31a25ff44c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-Input']/span/input</value>
      <webElementGuid>57d0c278-1647-4f5a-8133-6967bc15bed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/input</value>
      <webElementGuid>61fb6bcc-c9d8-4732-968f-3d8903f872f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'Input_PasswordVal']</value>
      <webElementGuid>b6b25637-d212-42ba-b9d9-def0da8bdfb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
