<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Operasional Cabang</name>
   <tag></tag>
   <elementGuidId>5276878c-3fdf-4f7d-b5fa-6e1822c78fa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0c411dcf-cc69-434d-a56c-74457703c79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>62e4f968-c84b-418b-8515-9588e040ae60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader</value>
      <webElementGuid>9dd2a2c7-5bb7-4ef5-8763-da304f4a3032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d49f965f-2396-4ab5-b362-ab0b250fca4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c6216981-6be0-4aeb-843a-b068f5e2d64f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-17_1-b4-l1-23_5-b1-Items</value>
      <webElementGuid>1bc1ad27-c48e-4656-bd13-22a01e3fd652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>4575cda8-501d-44fb-97a0-148f216f8dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92694e0d-bf24-4e76-8fa6-dd048ec38641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operasional Cabang</value>
      <webElementGuid>db73294d-5335-42fa-85e0-7f53fd9790d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader&quot;)</value>
      <webElementGuid>5cf3aa60-2869-4ec9-a83c-1550d9b8c724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader']</value>
      <webElementGuid>742471f3-7749-4617-811a-369f08055892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-17_1-b4-l1-23_5-b1-Submenu']/div</value>
      <webElementGuid>bf66db4e-993a-42cd-ac2d-506a59ea68c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showroom/Supplier'])[1]/following::div[4]</value>
      <webElementGuid>44772bc4-fcd0-4d18-a79a-856de1c4cd07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[1]/following::div[4]</value>
      <webElementGuid>abc8552e-8b26-4ffe-8c8c-7d78d4e69ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Petty Cash'])[1]/preceding::div[3]</value>
      <webElementGuid>63d82303-2cee-4209-9436-69fc97f8c595</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>5f8b1c16-ccc7-496f-aa8c-9f8cf78ba2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-17_1-b4-l1-23_5-b1-SubMenuHeader' and (text() = 'Operasional Cabang' or . = 'Operasional Cabang')]</value>
      <webElementGuid>7188d6f2-d527-4af5-8dc9-99746cbd9f4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
