<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah_1</name>
   <tag></tag>
   <elementGuidId>72d5ed3b-bcd5-4e62-a55d-0fe01bf7d5d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div/div[2]/form/div[6]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b4-b6-Button > button.btn.btn-limegreen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22987bc6-d0f6-46da-8698-16c47ef1064c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-limegreen</value>
      <webElementGuid>99490552-6e8e-4002-83fb-48f4fb8202e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9786c316-d722-4e33-924f-6694c267684c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>9b1d03b1-646e-4f81-a6e4-84f6c10560b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b4-b6-Button&quot;)/button[@class=&quot;btn btn-limegreen&quot;]</value>
      <webElementGuid>4e03c210-35c3-4b41-81e0-132ab35863d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>af538744-1b2a-43f0-95f3-b5de67d0b8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b4-b6-Button']/button</value>
      <webElementGuid>ee69a7c1-a605-40ba-b734-da8cd556565a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unggah'])[1]/following::button[1]</value>
      <webElementGuid>7426798f-744c-4f8b-8ba3-6144c9c7b9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>57621b1a-5af1-4bcb-a221-83d462b3cdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>f93a6ad0-02fc-463e-81c7-e3ff89bf73ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
