<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select StatusBaruPenugasanDalam Pros_c89740</name>
   <tag></tag>
   <elementGuidId>26fe0fab-79df-48d3-9a80-83cea33fbdaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[1]/div/div[2]/div[2]/div[1]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b1-DropdownStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e8eb62d4-07ff-4ee3-8943-3abee1359eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>04511667-d940-45eb-b16e-6869624d78de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5cbc4c72-12ac-4abd-bcd4-18a9ba752a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-DropdownStatus</value>
      <webElementGuid>9fce55be-9240-4d93-b95d-9c72793935a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select StatusBaruPenugasanDalam ProsesMenunggu PersetujuanDisetujuiDikembalikanTidak Selesai</value>
      <webElementGuid>b88a1277-cd38-4d6d-9b44-60d55732616f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b1-DropdownStatus&quot;)</value>
      <webElementGuid>1e333093-7f68-4318-816e-85b0f67cb800</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b2-b1-DropdownStatus']</value>
      <webElementGuid>c45f8b4c-8999-45ea-94b2-46a054f88add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b1-DropdownStatus-container']/select</value>
      <webElementGuid>daf325b7-bf98-4030-98d9-13bc88e9fb78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/following::select[1]</value>
      <webElementGuid>39ada600-1b92-4ac0-ab54-84f82f37a1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>edc8b00f-e476-4762-9ce5-34db9743843e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::select[1]</value>
      <webElementGuid>1d481f23-1e51-4a31-b727-8471239de670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::select[1]</value>
      <webElementGuid>1eb04100-9394-421b-9109-30dc18849f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>4bc6878d-377c-4189-817d-a5b9dcfc9a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b2-b1-DropdownStatus' and (text() = 'Select StatusBaruPenugasanDalam ProsesMenunggu PersetujuanDisetujuiDikembalikanTidak Selesai' or . = 'Select StatusBaruPenugasanDalam ProsesMenunggu PersetujuanDisetujuiDikembalikanTidak Selesai')]</value>
      <webElementGuid>fac936c8-9f21-4954-957e-75627e668ca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
