<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiBANDUNG ABU 1SURABAYA ABU _aaf35c</name>
   <tag></tag>
   <elementGuidId>53649e60-9dce-46f0-aa1d-f454464a490b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div/div[2]/form/div[2]/div/div/div[1]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b4-Branch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa09f451-3e19-4006-81f7-e6e653a62abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>a9fd1ba5-0f96-4b78-a35b-78be373b6f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d66f5221-a097-4173-8c90-d66f6643054d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b4-Branch</value>
      <webElementGuid>b1a85dd9-b8b6-4512-b7ae-5b09e385777e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiBANDUNG ABU 1SURABAYA ABU 1SEMARANG RBU 1JAKARTA ABU 1JAKARTA ABU 2JAKARTA ABU 3PALEMBANG ABU 1JAKARTA ABU 4PEKANBARU ABU 1TANGERANG ABU 1BALI ABU 1JAMBI ABU 1NDF BANDUNGNDF KALIMALANGNDF ALAM SUTRANDF DENPASARNDF JOGLOMALANG RBU 1BANJARMASIN RBU 1KARAWANG RBU 1PONTIANAK RBUPALANGKARAYA RBUMAKASAR ABU 1SAMPIT RBUBATAM RBU</value>
      <webElementGuid>944eebc6-ba0f-498d-b12d-0621453eb62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b4-Branch&quot;)</value>
      <webElementGuid>2a7b2d3b-79c8-4945-b199-14b09d13d65f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b2-b4-Branch']</value>
      <webElementGuid>40e43236-96dd-47f8-9884-8448cc23157b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b4-Branch-container']/select</value>
      <webElementGuid>3f03d3e2-3507-4c13-a967-d46b8564bb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch :'])[1]/following::select[1]</value>
      <webElementGuid>32e13588-63ef-4244-b5cc-73be181f42f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Claim :'])[1]/following::select[1]</value>
      <webElementGuid>39c1a70f-cae4-4e3c-a39c-1d44a782d3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penugasan :'])[1]/preceding::select[1]</value>
      <webElementGuid>85bc100f-df08-470c-918e-af5a59a8a945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::select[2]</value>
      <webElementGuid>65fd2d2e-0029-4354-b2ee-5f89ab2b1592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/select</value>
      <webElementGuid>6794fe9b-43bd-44fd-848d-81ebd4f176a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b2-b4-Branch' and (text() = 'Pilih OpsiBANDUNG ABU 1SURABAYA ABU 1SEMARANG RBU 1JAKARTA ABU 1JAKARTA ABU 2JAKARTA ABU 3PALEMBANG ABU 1JAKARTA ABU 4PEKANBARU ABU 1TANGERANG ABU 1BALI ABU 1JAMBI ABU 1NDF BANDUNGNDF KALIMALANGNDF ALAM SUTRANDF DENPASARNDF JOGLOMALANG RBU 1BANJARMASIN RBU 1KARAWANG RBU 1PONTIANAK RBUPALANGKARAYA RBUMAKASAR ABU 1SAMPIT RBUBATAM RBU' or . = 'Pilih OpsiBANDUNG ABU 1SURABAYA ABU 1SEMARANG RBU 1JAKARTA ABU 1JAKARTA ABU 2JAKARTA ABU 3PALEMBANG ABU 1JAKARTA ABU 4PEKANBARU ABU 1TANGERANG ABU 1BALI ABU 1JAMBI ABU 1NDF BANDUNGNDF KALIMALANGNDF ALAM SUTRANDF DENPASARNDF JOGLOMALANG RBU 1BANJARMASIN RBU 1KARAWANG RBU 1PONTIANAK RBUPALANGKARAYA RBUMAKASAR ABU 1SAMPIT RBUBATAM RBU')]</value>
      <webElementGuid>373ce8cc-d923-4ac6-9e86-a437dc6785aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
