<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 633,600.00_b3-b4-b6-l4_0-330_1-b4-_3da1a1</name>
   <tag></tag>
   <elementGuidId>cd0fe75b-3b4b-43e5-b4da-d97f7b0c1edc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b4-b6-l4_0-330_1-b4-Input_Mask']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b6-l4_0-330_1-b4-Input_Mask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89b6599b-7ab6-46a8-b501-36e126308a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-align-right OSFillParent masked-value</value>
      <webElementGuid>2bdf9587-c3bd-4a30-b71c-6364ffcef9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e2f1f31-d87c-4bf0-98b5-41b9dc7d0fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4b59bc7-a3f7-4c3d-8739-30087591d73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>633600</value>
      <webElementGuid>f4dc4830-cdd4-4ccd-9fb0-f68a2334d12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b6-l4_0-330_1-b4-Input_Mask</value>
      <webElementGuid>eef3eac8-f19f-4869-8e05-637523634352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c3c71566-8192-4e5c-8365-aff9da953645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b6-l4_0-330_1-b4-Input_Mask&quot;)</value>
      <webElementGuid>4abcebde-fa91-4a8a-abbc-9ebdea42546f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b6-l4_0-330_1-b4-Input_Mask']</value>
      <webElementGuid>ec2a6cca-1e38-4e09-9716-e7c600d239a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b6-l4_0-330_1-b4-MaskedContent']/span/input</value>
      <webElementGuid>bce5fff5-168b-4b33-92a4-63d9dc99c339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/div/div/div/div/div/span/input</value>
      <webElementGuid>e2e62311-2738-468b-996b-0b83e8565053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b4-b6-l4_0-330_1-b4-Input_Mask']</value>
      <webElementGuid>595e1517-b075-420c-8e44-5ecfd6a9ba21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
