<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 415,000.00_b3-b4-b6-l4_0-705_5-Inp_0bbf5e</name>
   <tag></tag>
   <elementGuidId>e95877ae-7d79-4628-be85-535e7f13a234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[6]/td[6]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b6-l4_0-705_5-Input_TanggalTransaksiKwitansi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a76ccb29-e128-4f7e-a13b-1f02ead2215d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>225251b2-bd5c-41ab-a7eb-1529e4248fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>445ed8e5-8357-420a-b432-465023f3e2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9e3f61f8-24ee-4de4-b502-22732963b199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2022-03-16</value>
      <webElementGuid>9eff8ee4-c9d4-41d1-bf4d-b31889c8c52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b6-l4_0-705_5-Input_TanggalTransaksiKwitansi</value>
      <webElementGuid>59a52255-e2e5-4239-b1c2-23eb1be1df7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b6-l4_0-705_5-Input_TanggalTransaksiKwitansi&quot;)</value>
      <webElementGuid>40dbbdbf-5cde-4850-99a8-54c24e42a599</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b6-l4_0-705_5-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>04584c15-8fdf-431a-a08d-64c6c1a97608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b4-b6-TableReimbursed']/tbody/tr[6]/td[6]/div/span/input</value>
      <webElementGuid>b1bc7c0b-dd8f-4baf-942e-b660738c5ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[6]/div/span/input</value>
      <webElementGuid>7149e418-3771-4d6d-b5e8-dab4205b0b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b4-b6-l4_0-705_5-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>8089faf0-88a1-4de8-9776-9983c07a6472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
