<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 1,050,000.00_b3-b4-b6-l4_0-705_3-I_fe66be</name>
   <tag></tag>
   <elementGuidId>0d236437-0654-4b0a-b4ed-8a29420045ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[4]/td[6]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b6-l4_0-705_3-Input_TanggalTransaksiKwitansi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e619b1d8-380d-48bf-9536-0f2a199c71f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>508247f3-5f12-4ce5-9d10-474f1711ddcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>9168c6c3-0ee3-48b2-9b33-3c871253209e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bf28ac7b-b758-47ab-abe5-668731a35dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2022-03-16</value>
      <webElementGuid>35fc36d5-0351-47cb-853f-88926c7678d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b6-l4_0-705_3-Input_TanggalTransaksiKwitansi</value>
      <webElementGuid>9b6cbbc8-e74c-4038-92ae-54eeea8068dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b6-l4_0-705_3-Input_TanggalTransaksiKwitansi&quot;)</value>
      <webElementGuid>c435bee2-b530-481e-8401-24feb29bd026</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b6-l4_0-705_3-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>a3a4c7c7-7c91-4a2c-baff-295a9d12fe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b3-b4-b6-TableReimbursed']/tbody/tr[4]/td[6]/div/span/input</value>
      <webElementGuid>7f4dbd13-2736-475a-a09a-bd3345ddbf58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/div/span/input</value>
      <webElementGuid>a141129b-c597-4154-b68f-0e0222eace27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b4-b6-l4_0-705_3-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>fb879802-aa93-4ee8-b8f0-dbb746508179</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
