<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp 53,000.00_b3-b4-b6-l4_0-705_4-b4-I_7216bf</name>
   <tag></tag>
   <elementGuidId>98a5389a-93f4-4051-9d55-79ebbbd7f1ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[5]/td[7]/div/div/div/div/div[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b6-l4_0-705_4-b4-Input_Mask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3795000-d346-439f-96e7-74432875f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-align-right OSFillParent masked-value</value>
      <webElementGuid>d78e8af0-f6f3-4277-aa85-d7f4ac60c18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3104d2e1-c58b-4405-9677-532b3ef47c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63c06d1f-561a-4727-b159-2776f28ea434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5e2a3ab-a9eb-4b64-b945-3b703c6bf287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b6-l4_0-705_4-b4-Input_Mask</value>
      <webElementGuid>c5cef4ff-44ee-4398-8734-b3bb970ba79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>d98fc983-dd23-4466-a628-631a6a167e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b6-l4_0-705_4-b4-Input_Mask&quot;)</value>
      <webElementGuid>c248626b-d124-4391-8fc4-ff2e571fe1a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b6-l4_0-705_4-b4-Input_Mask']</value>
      <webElementGuid>b1e63b7c-6592-4899-bbf0-5ea4dba11a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b6-l4_0-705_4-b4-MaskedContent']/span/input</value>
      <webElementGuid>c64f16c8-66ac-483a-97c8-69ebe0490ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[7]/div/div/div/div/div/span/input</value>
      <webElementGuid>05332b16-77d0-4d1c-979a-385ae082d347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b4-b6-l4_0-705_4-b4-Input_Mask']</value>
      <webElementGuid>2bc0e015-50e7-43ce-a788-50ef66b039d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
