<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiSesuaiTidak Sesuai_3</name>
   <tag></tag>
   <elementGuidId>3ae2f944-8f9f-47f1-8ec2-03b45fb96035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[1]/div[3]/div/div/table/tbody/tr[4]/td[10]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b6-l4_0-705_3-Kesesuaian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>879856c6-87d5-4989-90d0-059269f91b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>4c8da9e2-a2e9-4a36-9322-db0341575bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c02f38bf-28a3-4f6d-a9b1-09aaa538c4c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b6-l4_0-705_3-Kesesuaian</value>
      <webElementGuid>c8f28a38-3823-413b-8dbb-80eabd76ab92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiSesuaiTidak Sesuai</value>
      <webElementGuid>a33e6461-a2de-40b6-b2b4-208776ca533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b6-l4_0-705_3-Kesesuaian&quot;)</value>
      <webElementGuid>5cabce3f-5faa-44cd-ae97-0b2eca181e40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b4-b6-l4_0-705_3-Kesesuaian']</value>
      <webElementGuid>b40c39af-ecd8-483a-9428-4949dfdb2527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b6-l4_0-705_3-Kesesuaian-container']/select</value>
      <webElementGuid>762a65cb-7f2d-4c80-b7ab-98d8baea462d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1,050,000.00'])[2]/following::select[1]</value>
      <webElementGuid>2c880587-2553-48a6-88b0-6e75fbd96d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 1,050,000.00'])[1]/following::select[1]</value>
      <webElementGuid>cff11445-490c-47a8-a521-aa7c040d8e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[5]/preceding::select[2]</value>
      <webElementGuid>9c27bb41-90e0-49fe-bb8e-1df91710037f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automobile Expenses 2'])[2]/preceding::select[2]</value>
      <webElementGuid>41632e55-a7a0-4d95-aab6-8db57bf32f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[10]/div/div/select</value>
      <webElementGuid>f812a70c-797b-4d66-b276-fd2c82090e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b4-b6-l4_0-705_3-Kesesuaian' and (text() = 'Pilih OpsiSesuaiTidak Sesuai' or . = 'Pilih OpsiSesuaiTidak Sesuai')]</value>
      <webElementGuid>be1fa5ba-301a-4aac-bc8c-da92a55c8813</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
