<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Operasional Cabang</name>
   <tag></tag>
   <elementGuidId>6b157f12-a2ec-4724-aa26-b7d1b33d72e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[3]/div/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-47_9-b4-l1-71_5-b1-SubMenuHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ce63465-07aa-44a3-97a3-7bf1ff223087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>652c5c14-dc68-41ed-ba2a-6ec0fb54897b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-47_9-b4-l1-71_5-b1-SubMenuHeader</value>
      <webElementGuid>af8b95cf-4e99-4920-a263-5791167ae75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0cb0204f-dc6a-40f0-b69c-0fa2309391ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b359f63f-679d-45fc-a689-bc7f9cb850a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-47_9-b4-l1-71_5-b1-Items</value>
      <webElementGuid>54b68be2-00cb-4bd7-82d4-1a9aceb01036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>8d31c641-8014-4ce0-aff1-7ce31654370c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a4e130d-00a4-443c-9a75-03d7df1ecaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operasional Cabang</value>
      <webElementGuid>b3169cf4-a47f-40f8-99bf-5b57158f4281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-47_9-b4-l1-71_5-b1-SubMenuHeader&quot;)</value>
      <webElementGuid>3311afcd-172c-4604-948b-3bdb67c6f869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-47_9-b4-l1-71_5-b1-SubMenuHeader']</value>
      <webElementGuid>7f583ca8-95f2-40ba-a216-2ba0f9587b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-47_9-b4-l1-71_5-b1-Submenu']/div</value>
      <webElementGuid>29e824ac-f9a4-4917-a3ba-7e6dfc58c086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showroom/Supplier'])[2]/following::div[4]</value>
      <webElementGuid>53df4544-7005-4b8b-adb4-cb078a27f49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[2]/following::div[4]</value>
      <webElementGuid>b18d9740-fb7e-432c-93bb-cd3e616fafb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Petty Cash'])[2]/preceding::div[3]</value>
      <webElementGuid>43425292-1581-436c-b4b6-a6d22133d95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div/div/div</value>
      <webElementGuid>293ea729-3e08-4790-bd56-8966a67a9019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-47_9-b4-l1-71_5-b1-SubMenuHeader' and (text() = 'Operasional Cabang' or . = 'Operasional Cabang')]</value>
      <webElementGuid>38869462-912c-41ac-a4fc-d788ffc3f2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
