<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_b3-b1-l1_0-152_0-Check</name>
   <tag></tag>
   <elementGuidId>69c5a9d1-f534-43fc-a001-d488bfe62c57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type = 'checkbox' and @id = 'b3-b1-l1_0-152_0-Check']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-l1_0-152_0-Check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a75362e-41e9-456d-83e2-cb991f7515ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>98976c6b-2d60-49b9-adaa-0406400400dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ee213de5-74bd-4ce0-9671-2c51b04f144a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-l1_0-152_0-Check</value>
      <webElementGuid>a554b4c2-5d1f-4005-88b8-1e10ad13dbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-l1_0-152_0-Check&quot;)</value>
      <webElementGuid>cc89d23b-e1ad-4edb-8863-c437a7e682f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-l1_0-152_0-Check']</value>
      <webElementGuid>e8c4352c-8636-4856-ae2c-019c016ae748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-$b1']/div[2]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>7e30d5af-61b6-44af-ab81-de984244a61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>408b836d-f4bc-4b08-ae0f-0607dd837b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b1-l1_0-152_0-Check']</value>
      <webElementGuid>db509102-b253-4aa9-a33b-f9c6accef7a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
