<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Operasional Cabang_osui-submenu__header__icon</name>
   <tag></tag>
   <elementGuidId>b3b05991-d5a8-448f-826c-9c70d000768b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[3]/div/div/div[2]/div/div/div[2]/div/div/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-17_9-b4-l1-46_5-b1-SubMenuHeader > div.osui-submenu__header__icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46c86456-5767-4b22-9e65-bbe70f338952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header__icon</value>
      <webElementGuid>2b5fc7b6-2a4d-4b33-924c-36ab4eed26ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-17_9-b4-l1-46_5-b1-SubMenuHeader&quot;)/div[@class=&quot;osui-submenu__header__icon&quot;]</value>
      <webElementGuid>7eb0f93e-6ff9-4b47-b904-8c02b796fb22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-17_9-b4-l1-46_5-b1-SubMenuHeader']/div[2]</value>
      <webElementGuid>325bc220-a74c-4751-a000-fb7a06a3bfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div[2]/div/div/div/div[2]</value>
      <webElementGuid>2bb10ca9-65bb-43d8-892f-9c34a8ae0e1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
