<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_b3-b2-l1_0-152_0-Check</name>
   <tag></tag>
   <elementGuidId>6d06303a-24c2-4c47-9567-0dfb35c98b95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[2]/div[1]/table/tbody/tr[1]/td[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-l1_0-152_0-Check</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89c8ae49-1408-4c15-889f-b0bb83062b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>29036870-86ab-49e9-b607-a3f7fac90330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2eaf5685-93d8-4869-beab-b88dfdc8f70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-l1_0-152_0-Check</value>
      <webElementGuid>d56743b6-7c64-4297-b9ea-b29b8cb46e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-l1_0-152_0-Check&quot;)</value>
      <webElementGuid>fdc210c6-ea8c-4d5b-bd9a-aafce81ebc49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b2-l1_0-152_0-Check']</value>
      <webElementGuid>fcfdf665-1d86-4fd0-8905-9bcf2c206777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-$b2']/div[2]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>fa2722ed-7a97-41b9-a111-6d0d2f5a4247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input</value>
      <webElementGuid>69daf980-97ae-49b8-9cd9-2e56cdd827b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b2-l1_0-152_0-Check']</value>
      <webElementGuid>7260f948-c3a4-4dc9-b69b-0046397c4fd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
