<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiAdaTidak Ada_7</name>
   <tag></tag>
   <elementGuidId>3d41d528-a714-4c31-84ae-d1944fd59f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr[1]/td[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b8-l7_0-234_0-Keberadaan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eda80b59-e655-459c-ad9d-adc4391cdd5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>1c3f5cec-8877-4775-a8e4-35177d3545f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce80885b-4163-453b-8928-d1f9a49dba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b8-l7_0-234_0-Keberadaan</value>
      <webElementGuid>09da3479-9544-4650-ab37-68acb53a2818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiAdaTidak Ada</value>
      <webElementGuid>cdbd9c4c-17b8-4e72-8eee-445f43ba2bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b8-l7_0-234_0-Keberadaan&quot;)</value>
      <webElementGuid>d2179e84-613b-4449-aa91-509435b3a033</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b3-b8-l7_0-234_0-Keberadaan']</value>
      <webElementGuid>d026bca4-f5ac-43a6-bf22-94fea84067d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b8-l7_0-234_0-Keberadaan-container']/select</value>
      <webElementGuid>0b4ed826-36f8-49e5-a623-5b8a55ca093b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding Kas Kecil CBU - Proyek A'])[1]/following::select[1]</value>
      <webElementGuid>e93b9465-6875-4f3d-b663-e31e8151c392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[4]/following::select[1]</value>
      <webElementGuid>31a1783b-3631-4fa6-82bf-971cfa26af8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[20]/preceding::select[3]</value>
      <webElementGuid>fc786f5d-fd2e-461f-802a-c832091ed016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding Kas Kecil CBU - Audit'])[1]/preceding::select[3]</value>
      <webElementGuid>fab29d16-6481-4c67-86fc-d355751982b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr/td[2]/div/select</value>
      <webElementGuid>b38dd33d-27f6-4ad1-bb03-54244fce2f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b3-b8-l7_0-234_0-Keberadaan' and (text() = 'Pilih OpsiAdaTidak Ada' or . = 'Pilih OpsiAdaTidak Ada')]</value>
      <webElementGuid>0c777e6c-cfd7-4eb3-a9f4-694b5fe2b125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
