<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Klaim Kas Kecil CBU - Transportasi_227de5</name>
   <tag></tag>
   <elementGuidId>404d206b-bafa-4817-b10b-323e29da0c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[1]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr[1]/td[5]/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b3-b6-l8_0-184_0-TextArea_Catatan2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>52c5a143-3ab7-49e9-9656-d43be972bb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>a40d7a15-2596-4862-9eda-05fcdd6332b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>56c9fd22-7d49-46de-bdbf-7a01f93530b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>9387b952-22e5-418b-8ba7-eb49f040d3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b3-b6-l8_0-184_0-TextArea_Catatan2</value>
      <webElementGuid>ae50443b-756e-4685-a2d6-3c1f229eab65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b3-b6-l8_0-184_0-TextArea_Catatan2&quot;)</value>
      <webElementGuid>cb6bda1b-0e65-430b-ae9b-5666135d832e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b3-b6-l8_0-184_0-TextArea_Catatan2']</value>
      <webElementGuid>65170f76-097f-4dc7-bd06-055eec2443bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b3-b6-DokumenPersetujuan']/div[3]/div/table/tbody/tr/td[5]/span/textarea</value>
      <webElementGuid>a42bd2f6-b475-4bc6-a4ff-0d90f3988b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/span/textarea</value>
      <webElementGuid>3846fcce-dbf6-4aa8-ac8d-61177e61890f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b3-b6-l8_0-184_0-TextArea_Catatan2']</value>
      <webElementGuid>2d445178-c44e-4ae9-b8ef-4c934b0c00c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
