<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a categorySelesaiSedang Berja_127797</name>
   <tag></tag>
   <elementGuidId>42a298b3-5b16-4edd-a5e7-d368ff67c826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div/div/div/div/div[3]/div[2]/form/div/div/div[1]/div/div/div/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-l1-367_0-b2-TindakLanjutStatus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>31a93514-e8d3-4e7b-a6f6-a07fec7f57f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>c3e7b252-6433-487f-9881-0b894e946a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e28daff9-93c8-40e0-bd81-4668a0e39095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l1-367_0-b2-TindakLanjutStatus</value>
      <webElementGuid>462d60d8-97f4-4d48-ba48-552b08620cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a categorySelesaiSedang BerjalanBatal</value>
      <webElementGuid>9c6a3652-a10c-4126-bf14-afca3e5da16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l1-367_0-b2-TindakLanjutStatus&quot;)</value>
      <webElementGuid>d3d5681f-28e7-4901-9564-8ed0ce6bb4b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-l1-367_0-b2-TindakLanjutStatus']</value>
      <webElementGuid>b4fec481-bb63-44d5-9f7f-fc32d52062dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l1-367_0-b2-TindakLanjutStatus-container']/select</value>
      <webElementGuid>dfd7659d-fe2b-46d8-87ee-9c60f3e62dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[13]/following::select[1]</value>
      <webElementGuid>e128c465-5d0a-432e-8819-3362d30f6772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tindak Lanjut'])[2]/following::select[1]</value>
      <webElementGuid>b472423e-12aa-44ac-ade6-0ab397081b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[2]/preceding::select[1]</value>
      <webElementGuid>6fd63b05-aac9-48df-8949-d41d7e2affac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[14]/preceding::select[1]</value>
      <webElementGuid>56facd68-9930-4b21-a829-f04f6e934e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div[2]/div/select</value>
      <webElementGuid>d839bc23-222c-4a80-8f2f-b5eb22e07184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-l1-367_0-b2-TindakLanjutStatus' and (text() = 'Select a categorySelesaiSedang BerjalanBatal' or . = 'Select a categorySelesaiSedang BerjalanBatal')]</value>
      <webElementGuid>2423f3a0-f7ca-4404-b22b-7f68fa348395</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
