<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__b3-l1-367_0-b2-TextArea_TindakLan_3efd64</name>
   <tag></tag>
   <elementGuidId>7ea55b06-5819-495b-bf88-d17f125aa612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div/div/div/div/div[3]/div[2]/form/div/div/div[2]/div/div/div[2]/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-l1-367_0-b2-TextArea_TindakLanjutCatatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8332da77-6e6c-496a-abf4-a9367a62a603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>5e0794bf-5640-41cf-bae5-a6b14388e29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>61e1fdcb-76a5-417e-990a-6118fbfeee3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>82b82a2d-96fd-4b6f-a6e0-41038be065f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l1-367_0-b2-TextArea_TindakLanjutCatatan</value>
      <webElementGuid>ab760e1b-13ec-47b3-8fa4-883f4f66c1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l1-367_0-b2-TextArea_TindakLanjutCatatan&quot;)</value>
      <webElementGuid>4527cddb-19dc-4c88-8405-f9fa7aed4c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-l1-367_0-b2-TextArea_TindakLanjutCatatan']</value>
      <webElementGuid>3c7f3aaa-1311-4515-9e9c-36528317785b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l1-367_0-b2-b19-Column2']/span/textarea</value>
      <webElementGuid>ea80c9a7-478c-4609-add5-0efaad69f4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/textarea</value>
      <webElementGuid>e291ed23-6596-4d88-b523-5c0609eeccfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l1-367_0-b2-TextArea_TindakLanjutCatatan']</value>
      <webElementGuid>a28296d4-4399-4367-9987-ebb6c5663283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
