<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_b3-b4-b8-l3_0-268_0-b5-Input_Mask</name>
   <tag></tag>
   <elementGuidId>50c2c65d-b21e-4247-9c14-e70e22410136</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[1]/td[5]/div/div/div/div/div[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b8-l3_0-268_0-b5-Input_Mask</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a3de814-7ab5-43df-856f-8729504ed8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-align-right OSFillParent masked-value</value>
      <webElementGuid>71fb54f6-3ff0-44b9-99e5-f3dc4f8424c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1b43336-5b5e-4a6c-98a2-a27b9c5238b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d8f60d4-cb94-45ca-ab82-e858824372c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b8-l3_0-268_0-b5-Input_Mask</value>
      <webElementGuid>6e676971-1e8d-4f0d-a728-e58fdf69de9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ea929c84-df0f-4fec-ba85-3a8c5db69b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0.00</value>
      <webElementGuid>4a19166f-15de-4f7f-a7d8-d5ffafe79f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b8-l3_0-268_0-b5-Input_Mask&quot;)</value>
      <webElementGuid>0175ab83-5ee6-46fa-8a48-2ed38dd313fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b8-l3_0-268_0-b5-Input_Mask']</value>
      <webElementGuid>01e5990e-92b7-4f40-8332-7593bc943f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b8-l3_0-268_0-b5-MaskedContent']/span/input</value>
      <webElementGuid>60856ce6-834d-457c-b9cd-5e2eb1090086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/div/div/span/input</value>
      <webElementGuid>69ee4a09-ece8-4c28-9ac0-84c7e3c438b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b4-b8-l3_0-268_0-b5-Input_Mask' and @placeholder = 'Rp 0.00']</value>
      <webElementGuid>081260c5-ece2-49b7-a106-9506dba78de2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
