<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lihat Dokumen_b3-b4-b8-l3_0-268_1-Inp_5fb7d0</name>
   <tag></tag>
   <elementGuidId>e29fe8dd-e11b-42c5-ab5c-c955e1c99a13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[2]/td[4]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b8-l3_0-268_1-Input_TanggalTransaksiKwitansi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9704987c-60e8-4e16-afaa-ef4076ba5407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>2915b149-b861-4b32-96dc-ce162aa088c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>80162e38-38e5-4115-88a2-fec3324a97e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f3559b36-bb5d-4b9c-9863-9d7021948d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>1900-01-01</value>
      <webElementGuid>2330e54d-bd83-4d5e-b58c-b92140ee8cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b8-l3_0-268_1-Input_TanggalTransaksiKwitansi</value>
      <webElementGuid>5c5df72e-1eaa-4e40-9537-ad79f7984530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b8-l3_0-268_1-Input_TanggalTransaksiKwitansi&quot;)</value>
      <webElementGuid>1520c575-01e7-4c46-8cd8-2a89799ead55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b8-l3_0-268_1-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>b6645fdf-6386-4bfd-955b-87fc578fb0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b8-PettyCashOutStanding']/div[3]/div/table/tbody/tr[2]/td[4]/div/span/input</value>
      <webElementGuid>767d2865-48d0-4de0-b344-a9b829378671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/div/span/input</value>
      <webElementGuid>aa7b16e1-0486-4b5b-b293-323f7e4d8b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b4-b8-l3_0-268_1-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>9d3a98b1-3858-4611-9fe2-9eb1f7a30f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
