<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Action_b3-b4-b8-l3_0-268_0-Input_Tang_26adfb</name>
   <tag></tag>
   <elementGuidId>b0dca666-51c1-4614-b54a-ad21619fbd5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[1]/td[4]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b8-l3_0-268_0-Input_TanggalTransaksiKwitansi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dba7ec0c-2e49-43f3-936f-2103ca2cb224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>2949e3a5-c980-4c6b-ad86-13f79e74534b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>31cfcaef-caf7-4a50-b964-fe988667d31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f2a8f6b-48f9-46b2-9e51-f3c47048e65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2022-03-18</value>
      <webElementGuid>ea17eecc-6188-4d49-b491-b6ef4c898460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b8-l3_0-268_0-Input_TanggalTransaksiKwitansi</value>
      <webElementGuid>cbfda4e8-c901-4873-b9c8-7768362adfac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b8-l3_0-268_0-Input_TanggalTransaksiKwitansi&quot;)</value>
      <webElementGuid>24c394a0-6cc0-4d83-8c15-49656c2f45da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b8-l3_0-268_0-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>d76ca7d2-e2b2-468b-bb88-f245f07805d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b8-PettyCashOutStanding']/div[3]/div/table/tbody/tr/td[4]/div/span/input</value>
      <webElementGuid>5aafd3a7-cfd1-4529-bd3a-5a21c749ab2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/span/input</value>
      <webElementGuid>d0b6875d-c9c7-4119-a615-879cff86d234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b4-b8-l3_0-268_0-Input_TanggalTransaksiKwitansi']</value>
      <webElementGuid>16da21a7-0b8b-4e3d-8eb1-52d0c85e3d39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
