<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiSesuaiTidak Sesuai</name>
   <tag></tag>
   <elementGuidId>56f208d0-8566-4d04-89f2-10fedb9a842a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[3]/div/table/tbody/tr[1]/td[8]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b8-l3_0-268_0-Kesesuaian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>71765861-b3b0-4a3c-99be-e1b7745af1d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>014cac30-e817-4046-b4c7-e71ef39e7c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc380765-1409-454c-8494-23256119e457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b8-l3_0-268_0-Kesesuaian</value>
      <webElementGuid>953726cc-cad0-40b5-8e20-8fba0078b786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiSesuaiTidak Sesuai</value>
      <webElementGuid>21b7667e-083e-4027-b3cc-c5e10365082b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b8-l3_0-268_0-Kesesuaian&quot;)</value>
      <webElementGuid>d2c5dbf7-3bdd-49ab-ae7f-c2c97e9839bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b4-b8-l3_0-268_0-Kesesuaian']</value>
      <webElementGuid>0d9de26b-8091-4359-8d7e-b3c6d71f0dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b8-l3_0-268_0-Kesesuaian-container']/select</value>
      <webElementGuid>d8531c5b-efc8-432f-a92a-5d4f223152df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 0,00'])[1]/following::select[1]</value>
      <webElementGuid>837b1038-2fb4-4187-84a8-657df94f6b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[3]/following::select[1]</value>
      <webElementGuid>277f08d6-2bbb-4d42-a804-eae15e77eb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[14]/preceding::select[2]</value>
      <webElementGuid>dfac95e0-6eb4-497d-a668-59ce0310b24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 0,00'])[2]/preceding::select[2]</value>
      <webElementGuid>8485a974-04f8-403d-9b5e-a5a8f2c01b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/select</value>
      <webElementGuid>53ed34e4-cd6e-4e14-804e-05a4f7ba9dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b4-b8-l3_0-268_0-Kesesuaian' and (text() = 'Pilih OpsiSesuaiTidak Sesuai' or . = 'Pilih OpsiSesuaiTidak Sesuai')]</value>
      <webElementGuid>e6e7913b-47d8-4423-8cd4-f4e32ad1a294</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
