<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih kategori temuanRendahSedangTinggi</name>
   <tag></tag>
   <elementGuidId>5b92af26-41ce-4577-ad57-157ab3c1f793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[1]/div[4]/div/div/div[2]/div/div/div[1]/div/div[6]/div/div/div[2]/div/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b8-b8-KategoriTemuanDropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4a650175-dfe9-4db6-83e0-1603a904ce63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>4705a2ab-ff17-4797-b65a-bdb554b9903f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e39a07b4-6ec4-406d-a4ba-f91c59e48eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b8-b8-KategoriTemuanDropdown</value>
      <webElementGuid>84975917-9a13-4e3c-bd32-c53f78036ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih kategori temuanRendahSedangTinggi</value>
      <webElementGuid>dd35fedb-c0c5-4c91-a2ed-c9ee106b1701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b8-b8-KategoriTemuanDropdown&quot;)</value>
      <webElementGuid>d5e918ca-2442-41a9-9a40-c8d1fac39711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b4-b8-b8-KategoriTemuanDropdown']</value>
      <webElementGuid>375cc95c-e033-4222-ac0f-c27c1f255a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b8-b8-KategoriTemuanDropdown-container']/select</value>
      <webElementGuid>9c2de01b-e63e-4a87-8713-7483d3ec6ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[10]/following::select[1]</value>
      <webElementGuid>bfe28cbf-7704-47db-9bd0-37d0141f7b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori Temuan'])[4]/following::select[1]</value>
      <webElementGuid>8e5db572-f56f-41d7-ae33-37afe8038ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[4]/preceding::select[1]</value>
      <webElementGuid>d9debad1-2e48-4871-9170-143e94e3c002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[11]/preceding::select[1]</value>
      <webElementGuid>9e23c3ae-7e09-4477-8af7-24f0095a9c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>86d14ddb-4003-4a84-96f4-af40f64893f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b4-b8-b8-KategoriTemuanDropdown' and (text() = 'Pilih kategori temuanRendahSedangTinggi' or . = 'Pilih kategori temuanRendahSedangTinggi')]</value>
      <webElementGuid>5b152c2c-616f-41af-9e30-39bd6fdfee58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
