<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiTepatTidak Tepat</name>
   <tag></tag>
   <elementGuidId>707401a2-9647-4620-8023-66e0bff94b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div[1]/section/section/div/div[2]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr[1]/td[3]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b8-l7_0-198_0-Kesesuaian3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c2e106be-a9a4-449d-a4f8-c763ff4daeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>89d29329-bb36-432b-bbe5-1f6e2ded381c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>92fd7a8f-419e-405c-a79b-25fe5e192b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b8-l7_0-198_0-Kesesuaian3</value>
      <webElementGuid>393548ca-054e-42a9-9dfd-58520c673344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiTepatTidak Tepat</value>
      <webElementGuid>ea27c48f-a76b-4597-ad92-188ff6a5e52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b8-l7_0-198_0-Kesesuaian3&quot;)</value>
      <webElementGuid>d0a7979a-ffb5-4fc4-8248-77f385280437</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b4-b8-l7_0-198_0-Kesesuaian3']</value>
      <webElementGuid>891decdb-dbd5-4b53-b56a-82b37fc490a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b8-l7_0-198_0-Kesesuaian3-container']/select</value>
      <webElementGuid>14d33a86-96ba-443e-8ac9-505ecc43e81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding Kas Kecil RBU - Kebutuhan Cabang A'])[1]/following::select[2]</value>
      <webElementGuid>090ca327-0b5f-4030-97fc-37a59734b277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[4]/following::select[2]</value>
      <webElementGuid>37c6c2e9-0d08-46dc-aaae-b661067fe3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Dokumen'])[18]/preceding::select[2]</value>
      <webElementGuid>b9e5b19c-3db2-4fa2-a468-64a9fa65ca82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outstanding Kas Kecil RBU - Inventaris Kantor'])[1]/preceding::select[2]</value>
      <webElementGuid>0e6c88b6-0c12-4292-a2c5-41eec2187dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/div/div/div/div[2]/div[3]/div/table/tbody/tr/td[3]/div/select</value>
      <webElementGuid>502e2942-6a5e-4e24-9d4a-bfb9f60daec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b4-b8-l7_0-198_0-Kesesuaian3' and (text() = 'Pilih OpsiTepatTidak Tepat' or . = 'Pilih OpsiTepatTidak Tepat')]</value>
      <webElementGuid>45bbe67e-60ba-4763-83a7-31cfe260da80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
