<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__b3-b2-b1-StartDate</name>
   <tag></tag>
   <elementGuidId>e60fa4dd-4627-4b75-a31f-19ac6c8c9f29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[1]/div[2]/span[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b1-StartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ace8b272-0164-4240-b345-a57032556181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>153abe4b-ad1b-4a01-bb2e-515ea34c13cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>6f89cc43-43e0-4f57-9c19-4cac9a19b057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a838aaa1-f20b-4e9b-91b7-f8fcee25433b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-03-11</value>
      <webElementGuid>f6eb8662-b7a5-4fa4-b6ee-3bbb1dac5e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-StartDate</value>
      <webElementGuid>db3ef5a5-1bc7-42f3-85a1-76f66789e845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b1-StartDate&quot;)</value>
      <webElementGuid>b3ed1973-6e8d-45a5-a422-d6fc51d50d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b2-b1-StartDate']</value>
      <webElementGuid>b6cd97d2-5421-43d5-9d8a-d406be3aea6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-$b1']/div/div/div[2]/span/input</value>
      <webElementGuid>0ead65f8-e599-4b5b-a260-3fe8269e8bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/span/input</value>
      <webElementGuid>2fbed6d8-ad43-4f81-b141-a612a9efc3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-b1-StartDate']</value>
      <webElementGuid>84f56f9e-a217-4312-afb8-313e8c6bb827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
