<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unggah_3</name>
   <tag></tag>
   <elementGuidId>55ccd2cc-82ad-4b9b-bed9-fe2e5edefde3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[4]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.shadow-m.upload-file-button.background-green-dark.ThemeGrid_Width2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d3bdfdd-1f6c-40e0-a724-e861185c435a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary shadow-m upload-file-button background-green-dark ThemeGrid_Width2</value>
      <webElementGuid>785b2898-1866-4364-977b-d55478082132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1451b52-698d-4735-a499-f3390479794f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>ef5ae1f4-d94b-4b67-ac73-668e6e52ba2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b8-b4-$b42&quot;)/div[@class=&quot;margin-top-m&quot;]/button[@class=&quot;btn btn-primary shadow-m upload-file-button background-green-dark ThemeGrid_Width2&quot;]</value>
      <webElementGuid>f902565f-7ea2-4de3-8b82-daf6c422993a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>0924177f-5e29-4eae-9ded-d034159dff15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b8-b4-$b42']/div[4]/button</value>
      <webElementGuid>c38ca172-a951-4e4a-b4b4-8228a24baf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='loremipsum1.pdf'])[2]/following::button[1]</value>
      <webElementGuid>5b9a497f-86aa-42fe-9198-89a3a84bb1b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Date'])[1]/following::button[1]</value>
      <webElementGuid>699a4797-cccf-4cd7-97ce-bff5c2ccc078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[4]/button</value>
      <webElementGuid>2517721f-2c59-4313-8921-b5d62cb0a146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>c1959967-2627-4867-85a2-4e01aca5365f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
