<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BARU_b3-b1-b6-l4_0-845_0-TenggatWaktu_2f8543</name>
   <tag></tag>
   <elementGuidId>04ebbe86-4f11-41e4-8e58-f375fd50ccf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div[3]/div/section/section/div/div[1]/article/div/div/div[2]/div[2]/div/table/tbody/tr/td[9]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b6-l4_0-845_0-TenggatWaktuPenyelesaian2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9a2cb88-aae5-4178-9fe5-f8ef07ff89f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>9802c1e0-4137-4a62-891c-209a96bdb0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>435f9e4c-87ea-4c98-8c69-2c83c68d5c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4bf580f-9720-4d25-8f32-52a60c25fd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b6-l4_0-845_0-TenggatWaktuPenyelesaian2</value>
      <webElementGuid>2618b529-bdd3-4e50-afc2-b9d4c6c9787c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b6-l4_0-845_0-TenggatWaktuPenyelesaian2&quot;)</value>
      <webElementGuid>72357419-a259-470e-ae95-3634b1f34e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b6-l4_0-845_0-TenggatWaktuPenyelesaian2']</value>
      <webElementGuid>e4907440-c7e9-4d31-ae7c-57f3426327bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b6-DokumenPersetujuan']/div[2]/div/table/tbody/tr/td[9]/span/input</value>
      <webElementGuid>9d9d291f-d2a8-408d-a383-fec5d960f462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/span/input</value>
      <webElementGuid>ed849761-097c-45da-9131-d7e0ea3ec257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b6-l4_0-845_0-TenggatWaktuPenyelesaian2']</value>
      <webElementGuid>df965935-5ed3-4197-b611-3d17e5c11fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
