<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__b3-b1-b8-b4-Input_TenggatWaktuPenyelesaian</name>
   <tag></tag>
   <elementGuidId>3a45e5c1-68c8-46c5-9853-5347dd2558e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div[3]/div/section/section/div/div[2]/article/div/div/div[1]/div[2]/div/div/div[2]/div/div/div[1]/div[4]/div/div/div/div[2]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b8-b4-Input_TenggatWaktuPenyelesaian</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12eaadf0-0979-4992-97d1-9854c2f88417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>23d532e9-d7ed-4c04-bafd-299677d25401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c2d169b0-103f-4d3b-8a54-fd380eb2447c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>52bcca27-f983-401f-95c4-9badfcb0f128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b8-b4-Input_TenggatWaktuPenyelesaian</value>
      <webElementGuid>475dac7b-f456-4751-a90f-677ff724acc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b8-b4-Input_TenggatWaktuPenyelesaian&quot;)</value>
      <webElementGuid>f99ef488-21a4-4dc7-867a-e9d62604c9ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b8-b4-Input_TenggatWaktuPenyelesaian']</value>
      <webElementGuid>d2214bcd-538b-464e-ae76-ebd7ef4ca8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b8-b4-b25-Column2']/div/span/input</value>
      <webElementGuid>23b7939f-ce18-4563-970e-cf2bbbf82860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>70561e96-80b4-4b1b-bcc0-2c72e68739c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b8-b4-Input_TenggatWaktuPenyelesaian']</value>
      <webElementGuid>836ee988-5378-4652-8590-9af918644512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
