<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__b3-b1-b8-b4-TextArea_TindakLanjut</name>
   <tag></tag>
   <elementGuidId>bfc92b37-f573-4164-8220-43fa15781733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b3-b1-b8-b4-TextArea_TindakLanjut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b8-b4-TextArea_TindakLanjut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>daee4f6b-b4eb-4ccf-94a8-510b043a49db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>9d238984-7c83-4d04-8566-dc3d48a0fef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e46e8984-01ce-4c7d-a16a-148587f4f626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>34b4e315-6a47-468f-9aa2-802099db23f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b8-b4-TextArea_TindakLanjut</value>
      <webElementGuid>35288b5d-d98d-43d1-89e5-8eec6609d2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b8-b4-TextArea_TindakLanjut&quot;)</value>
      <webElementGuid>abf1b01b-41e2-4159-9991-b95955a6830b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b1-b8-b4-TextArea_TindakLanjut']</value>
      <webElementGuid>a3209259-65bb-410a-adb6-b074494d1932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b8-b4-b27-Column2']/div/span/textarea</value>
      <webElementGuid>e776fb8c-93f5-45dd-a735-e236b6291bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>22d3ed11-a6bf-42f4-b627-f4f1b0ad7a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b1-b8-b4-TextArea_TindakLanjut']</value>
      <webElementGuid>3c1761a3-9e5f-495f-b284-e356c4ff5598</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
