<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih OpsiSEMARANGSURABAYAJAKARTA GR_05f5b9</name>
   <tag></tag>
   <elementGuidId>8c40d084-983f-4c24-81a7-82629ba32800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div/div[2]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b1-DropdownCabang</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9455f51f-7d6f-4f6f-80a5-91a9eafce0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>a5bab118-fbea-4bae-b9b6-2116bb18513e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a67f6db3-aa01-46ff-928d-b81fc6346986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b1-DropdownCabang</value>
      <webElementGuid>919f7694-4745-4f30-a655-8ec324a75d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH</value>
      <webElementGuid>6a05c478-5508-4428-9988-9474d44a927c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b1-DropdownCabang&quot;)</value>
      <webElementGuid>6dcb6411-13de-43ec-9d28-9067dba27675</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-b1-DropdownCabang']</value>
      <webElementGuid>a80c3d1a-6da4-4033-8fe0-f635be0bf335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-b1-DropdownCabang-container']/select</value>
      <webElementGuid>d4f06b0b-f7df-42e8-bf9e-93a7afdd2975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[2]/following::select[1]</value>
      <webElementGuid>0f20a41e-ea98-45b1-8619-ba1cb1c64887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/following::select[1]</value>
      <webElementGuid>66110467-ac51-4eb5-8b3b-d000dd56c817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>4bf6a402-f71c-4ffe-ab8a-1c7df720c344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[3]/preceding::select[1]</value>
      <webElementGuid>b9deae6a-23cc-4804-800f-f60b63eae81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>1b95eeb3-3a1e-4bf6-aaf9-304c6fbcd288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-b1-DropdownCabang' and (text() = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH' or . = 'Pilih OpsiSEMARANGSURABAYAJAKARTA GROUPJAKARTA 1JAKARTA 2JAKARTA 3PEKANBARUPALEMBANGJAMBIBALIKPAPANSAMARINDABANJARMASINPONTIANAKMAKASARMANADOJAKARTA 1 SYARIAH')]</value>
      <webElementGuid>bc33145e-ab4c-4ee0-a6bf-06aa58c22c69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
