<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OUTSTANDING PETTY CASH</name>
   <tag></tag>
   <elementGuidId>c85d3db2-8dbe-48a0-889e-11935ccb05c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div/div/div[3]/div/section/header/div[1]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b4-Title > div.bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c35a80e4-5d6b-49b4-b341-fa7c92ad3c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bold</value>
      <webElementGuid>31c52f8b-5443-42cf-b801-0938b43f7112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OUTSTANDING PETTY CASH</value>
      <webElementGuid>2991b5d2-8090-4e6e-a903-bc25331e4190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b4-Title&quot;)/div[@class=&quot;bold&quot;]</value>
      <webElementGuid>753f15e7-c0a5-4c1e-beed-787a18144531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b4-Title']/div</value>
      <webElementGuid>54c1cdd8-e34d-4738-a84e-8fb183ef6e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PETTY CASH REIMBURSED'])[1]/following::div[3]</value>
      <webElementGuid>9e23e38d-6108-40ff-a6e7-a495c66f9c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::div[9]</value>
      <webElementGuid>2ef5b9ab-696e-4d3f-96e6-e7c1ca82dc87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Allocation'])[1]/preceding::div[2]</value>
      <webElementGuid>72dbd697-6490-435b-9bc4-e0bf35ca6d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Petty Cash'])[1]/preceding::div[2]</value>
      <webElementGuid>1683ad25-0f18-4b64-81a3-102e0daf9d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OUTSTANDING PETTY CASH']/parent::*</value>
      <webElementGuid>22e2f7a8-26a1-4282-bc1a-f59634bdc438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/div/div</value>
      <webElementGuid>08013d52-c2a2-4d56-8069-c87a331d7a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OUTSTANDING PETTY CASH' or . = 'OUTSTANDING PETTY CASH')]</value>
      <webElementGuid>166f42f9-03cb-448b-94aa-98bcae199305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
